//! Unsupervised LDA topic modeling over per-region token bags.
//!
//! Discovers latent token groups ("topics") in a mixed-content file without
//! requiring labelled training data. Each topic is a distribution over tokens;
//! each region is represented as a mixture of topics. Topics may correspond to
//! language families, obfuscation styles, or unknown patterns in the corpus.
//!
//! This is exploratory tooling — output is topic-word lists, not language
//! labels. It does not integrate into the main verdict path.
//!
//! Implementation: mean-field variational EM (simpler and faster than Gibbs
//! sampling for small corpora). Convergence is approximate; running more
//! iterations (`lda_iters`) improves stability.

/// One discovered topic: its index and the most representative tokens.
#[derive(Debug, Clone)]
pub struct Topic {
    pub index: usize,
    /// Top tokens for this topic sorted by weight descending.
    pub top_tokens: Vec<(String, f64)>,
}

/// Per-document topic distribution.
#[derive(Debug, Clone)]
pub struct DocumentTopics {
    /// `proportions[k]` = estimated proportion of topic k in this document.
    pub proportions: Vec<f64>,
}

/// Result of LDA inference on a set of documents (windows).
#[derive(Debug)]
pub struct LdaResult {
    pub topics: Vec<Topic>,
    pub documents: Vec<DocumentTopics>,
}

// ── Hyperparameters ──────────────────────────────────────────────────────────

const ALPHA: f64 = 0.1; // Dirichlet prior on per-document topic proportions
const BETA: f64 = 0.01; // Dirichlet prior on per-topic word proportions
const TOP_TOKENS_PER_TOPIC: usize = 10;

// ── Public API ───────────────────────────────────────────────────────────────

/// Run LDA on `documents` (each a token-count map) with `n_topics` topics
/// and `iters` variational EM iterations.
///
/// `documents`: each `Vec<(String, u32)>` is a sparse token frequency list
///   for one region. Typically generated by calling
///   `polyglot_tokenizer::get_linguist_tokens` on each window's text and
///   counting token occurrences.
pub fn run_lda(
    documents: &[Vec<(String, u32)>],
    n_topics: usize,
    iters: usize,
) -> LdaResult {
    if documents.is_empty() || n_topics == 0 {
        return LdaResult { topics: vec![], documents: vec![] };
    }

    // Build vocabulary.
    let mut vocab: Vec<String> = Vec::new();
    for doc in documents {
        for (token, _) in doc {
            if !vocab.contains(token) {
                vocab.push(token.clone());
            }
        }
    }
    let vocab_size = vocab.len();
    if vocab_size == 0 {
        return LdaResult { topics: vec![], documents: vec![] };
    }
    let token_idx: std::collections::HashMap<&str, usize> = vocab
        .iter()
        .enumerate()
        .map(|(i, t)| (t.as_str(), i))
        .collect();

    // Convert documents to dense integer bags.
    let docs_bow: Vec<Vec<(usize, u32)>> = documents
        .iter()
        .map(|doc| {
            doc.iter()
                .filter_map(|(t, c)| token_idx.get(t.as_str()).map(|&i| (i, *c)))
                .collect()
        })
        .collect();

    let n_docs = docs_bow.len();

    // ── Variational parameters ───────────────────────────────────────────────
    // gamma[d][k] = variational parameter for document-topic distribution
    //   (approximates Dirichlet posterior, initialize uniformly + ALPHA).
    // lambda[k][w] = variational parameter for topic-word distribution.
    let mut gamma: Vec<Vec<f64>> = vec![vec![ALPHA + 1.0; n_topics]; n_docs];
    let mut lambda: Vec<Vec<f64>> =
        vec![vec![BETA + 1.0 / vocab_size as f64; vocab_size]; n_topics];

    // ── Variational EM ───────────────────────────────────────────────────────
    for _iter in 0..iters {
        // E-step: update phi (variational per-word topic assignment) and gamma.
        let mut new_gamma: Vec<Vec<f64>> = vec![vec![ALPHA; n_topics]; n_docs];

        // Per-topic digamma for lambda row sums (needed for log E[beta]).
        let lambda_row_sums: Vec<f64> = lambda.iter().map(|row| row.iter().sum::<f64>()).collect();

        for (d, doc) in docs_bow.iter().enumerate() {
            // digamma(gamma[d][k]) - digamma(sum_k gamma[d][k])
            let gamma_sum = gamma[d].iter().sum::<f64>();
            let psi_gamma: Vec<f64> = gamma[d].iter().map(|&g| digamma(g) - digamma(gamma_sum)).collect();

            for &(w, count) in doc {
                // phi[w][k] ∝ exp(psi_gamma[k] + psi_lambda[k][w] - psi_lambda_sum[k])
                let mut phi: Vec<f64> = (0..n_topics)
                    .map(|k| {
                        let psi_lam = digamma(lambda[k][w]) - digamma(lambda_row_sums[k]);
                        (psi_gamma[k] + psi_lam).exp()
                    })
                    .collect();
                let phi_sum: f64 = phi.iter().sum();
                if phi_sum > 0.0 {
                    for v in phi.iter_mut() { *v /= phi_sum; }
                }
                for k in 0..n_topics {
                    new_gamma[d][k] += phi[k] * count as f64;
                }
            }
        }
        gamma = new_gamma;

        // M-step: update lambda.
        let mut new_lambda: Vec<Vec<f64>> = vec![vec![BETA; vocab_size]; n_topics];
        let lambda_row_sums: Vec<f64> = lambda.iter().map(|row| row.iter().sum::<f64>()).collect();

        for (d, doc) in docs_bow.iter().enumerate() {
            let gamma_sum = gamma[d].iter().sum::<f64>();
            let psi_gamma: Vec<f64> = gamma[d].iter().map(|&g| digamma(g) - digamma(gamma_sum)).collect();

            for &(w, count) in doc {
                let mut phi: Vec<f64> = (0..n_topics)
                    .map(|k| {
                        let psi_lam = digamma(lambda[k][w]) - digamma(lambda_row_sums[k]);
                        (psi_gamma[k] + psi_lam).exp()
                    })
                    .collect();
                let phi_sum: f64 = phi.iter().sum();
                if phi_sum > 0.0 {
                    for v in phi.iter_mut() { *v /= phi_sum; }
                }
                for k in 0..n_topics {
                    new_lambda[k][w] += phi[k] * count as f64;
                }
            }
        }
        lambda = new_lambda;
    }

    // ── Extract topics ───────────────────────────────────────────────────────
    let topics: Vec<Topic> = (0..n_topics)
        .map(|k| {
            let row_sum: f64 = lambda[k].iter().sum();
            let mut token_weights: Vec<(String, f64)> = vocab
                .iter()
                .enumerate()
                .map(|(w, token)| {
                    let weight = if row_sum > 0.0 { lambda[k][w] / row_sum } else { 0.0 };
                    (token.clone(), weight)
                })
                .collect();
            token_weights.sort_by(|a, b| b.1.partial_cmp(&a.1).unwrap_or(std::cmp::Ordering::Equal));
            token_weights.truncate(TOP_TOKENS_PER_TOPIC);
            Topic { index: k, top_tokens: token_weights }
        })
        .collect();

    // ── Extract per-document topic proportions ───────────────────────────────
    let documents_out: Vec<DocumentTopics> = gamma
        .into_iter()
        .map(|row| {
            let sum: f64 = row.iter().sum();
            let proportions = if sum > 0.0 {
                row.iter().map(|&v| v / sum).collect()
            } else {
                vec![1.0 / n_topics as f64; n_topics]
            };
            DocumentTopics { proportions }
        })
        .collect();

    LdaResult { topics, documents: documents_out }
}

// ── Digamma approximation ────────────────────────────────────────────────────
// Asymptotic expansion valid for x > 0. Sufficient precision for LDA.
fn digamma(mut x: f64) -> f64 {
    let mut result = 0.0;
    while x < 6.0 {
        result -= 1.0 / x;
        x += 1.0;
    }
    result += x.ln() - 1.0 / (2.0 * x) - 1.0 / (12.0 * x * x)
        + 1.0 / (120.0 * x * x * x * x);
    result
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_doc(pairs: &[(&str, u32)]) -> Vec<(String, u32)> {
        pairs.iter().map(|(t, c)| (t.to_string(), *c)).collect()
    }

    #[test]
    fn empty_input_returns_empty() {
        let r = run_lda(&[], 5, 10);
        assert!(r.topics.is_empty());
        assert!(r.documents.is_empty());
    }

    #[test]
    fn zero_topics_returns_empty() {
        let docs = vec![make_doc(&[("fn", 5), ("let", 3)])];
        let r = run_lda(&docs, 0, 10);
        assert!(r.topics.is_empty());
    }

    #[test]
    fn topic_count_matches_n_topics() {
        let docs = vec![
            make_doc(&[("fn", 10), ("let", 8), ("match", 5)]),
            make_doc(&[("def", 10), ("import", 8), ("return", 5)]),
        ];
        let r = run_lda(&docs, 3, 20);
        assert_eq!(r.topics.len(), 3);
    }

    #[test]
    fn document_proportions_sum_to_one() {
        let docs = vec![
            make_doc(&[("fn", 5), ("let", 3)]),
            make_doc(&[("def", 4), ("class", 6)]),
        ];
        let r = run_lda(&docs, 2, 15);
        for doc in &r.documents {
            let sum: f64 = doc.proportions.iter().sum();
            assert!((sum - 1.0).abs() < 1e-6, "proportions sum = {}", sum);
        }
    }

    #[test]
    fn topic_top_tokens_not_empty() {
        let docs = vec![make_doc(&[("fn", 10), ("let", 5), ("match", 3)])];
        let r = run_lda(&docs, 2, 10);
        for topic in &r.topics {
            assert!(!topic.top_tokens.is_empty());
        }
    }

    #[test]
    fn digamma_positive_values() {
        assert!(digamma(1.0).is_finite());
        assert!(digamma(10.0).is_finite());
        assert!(digamma(0.1).is_finite());
    }
}
