mod classifier;
pub mod ensemble;
pub mod mixture;
pub mod entropy;
mod extensions;
mod filenames;
mod heuristics;
pub mod hierarchy;
mod interpreters;
pub mod linear_chargram;
mod specializations;
pub mod structure;
mod tficf_classifier;

pub use classifier::{classify, classify_scored};
pub use entropy::byte_stats;
pub use extensions::{get_extension, get_languages_from_extension};
pub use filenames::get_language_from_filename;
pub use heuristics::get_languages_from_heuristics;
pub use hierarchy::filter_to_majority_family;
pub use interpreters::get_languages_from_shebang;
pub use linear_chargram::{classify_linear, classify_linear_scored};
pub use specializations::apply_specialization;
pub use structure::{detect_structure, StructureHit};
pub use tficf_classifier::{classify_tficf, classify_tficf_scored};
