static EXTENSIONS: phf::Map<&'static str, &[&str]> =
::phf::Map {
    key: 12913932095322966823,
    disps: &[
        (0, 65),
        (0, 275),
        (0, 820),
        (0, 13),
        (0, 9),
        (0, 380),
        (0, 4),
        (0, 820),
        (0, 3),
        (0, 67),
        (0, 260),
        (0, 0),
        (0, 131),
        (0, 5),
        (0, 30),
        (0, 103),
        (1, 342),
        (0, 943),
        (0, 33),
        (0, 5),
        (0, 3),
        (0, 0),
        (0, 972),
        (0, 21),
        (0, 774),
        (0, 13),
        (0, 0),
        (0, 7),
        (0, 1),
        (0, 0),
        (0, 66),
        (0, 12),
        (0, 6),
        (0, 52),
        (0, 1),
        (0, 4),
        (0, 0),
        (0, 26),
        (0, 66),
        (0, 37),
        (1, 1),
        (0, 56),
        (0, 139),
        (0, 93),
        (0, 80),
        (0, 8),
        (0, 4),
        (0, 0),
        (0, 35),
        (0, 2),
        (1, 343),
        (0, 157),
        (0, 22),
        (0, 140),
        (0, 155),
        (0, 6),
        (0, 805),
        (0, 8),
        (0, 754),
        (0, 21),
        (0, 318),
        (0, 1),
        (0, 209),
        (0, 4),
        (0, 14),
        (2, 362),
        (0, 446),
        (0, 1),
        (0, 0),
        (1, 194),
        (1, 657),
        (0, 35),
        (0, 12),
        (0, 522),
        (0, 2),
        (0, 284),
        (1, 9),
        (0, 23),
        (0, 106),
        (0, 295),
        (0, 81),
        (0, 11),
        (0, 706),
        (0, 3),
        (0, 2),
        (0, 6),
        (0, 1),
        (0, 3),
        (0, 17),
        (0, 8),
        (0, 88),
        (1, 18),
        (0, 150),
        (0, 33),
        (2, 253),
        (0, 12),
        (0, 255),
        (0, 374),
        (0, 43),
        (0, 7),
        (0, 431),
        (0, 1138),
        (0, 46),
        (0, 13),
        (0, 892),
        (0, 843),
        (0, 145),
        (0, 11),
        (0, 270),
        (0, 3),
        (0, 3),
        (6, 855),
        (0, 143),
        (0, 0),
        (0, 1094),
        (0, 44),
        (0, 28),
        (0, 233),
        (0, 2),
        (0, 792),
        (0, 756),
        (3, 1031),
        (3, 645),
        (0, 335),
        (0, 0),
        (0, 101),
        (1, 681),
        (0, 58),
        (0, 383),
        (0, 12),
        (0, 0),
        (1, 59),
        (10, 93),
        (0, 473),
        (0, 198),
        (0, 609),
        (0, 502),
        (3, 910),
        (0, 16),
        (0, 0),
        (0, 57),
        (0, 142),
        (0, 3),
        (3, 792),
        (0, 1),
        (0, 140),
        (0, 1),
        (4, 947),
        (0, 637),
        (1, 63),
        (0, 2),
        (3, 403),
        (0, 620),
        (1, 904),
        (0, 4),
        (0, 34),
        (3, 113),
        (0, 533),
        (0, 177),
        (0, 10),
        (0, 213),
        (3, 966),
        (1, 954),
        (3, 665),
        (0, 33),
        (0, 5),
        (0, 13),
        (0, 316),
        (0, 163),
        (0, 152),
        (0, 403),
        (0, 0),
        (0, 406),
        (0, 48),
        (0, 70),
        (0, 151),
        (1, 1058),
        (0, 6),
        (0, 112),
        (0, 943),
        (0, 228),
        (0, 300),
        (0, 353),
        (7, 426),
        (0, 0),
        (0, 150),
        (0, 8),
        (0, 351),
        (0, 0),
        (2, 260),
        (0, 350),
        (27, 40),
        (0, 1070),
        (0, 3),
        (4, 179),
        (0, 1),
        (0, 771),
        (0, 37),
        (0, 0),
        (0, 76),
        (0, 649),
        (0, 6),
        (0, 2),
        (0, 8),
        (1, 789),
        (0, 388),
        (0, 37),
        (0, 564),
        (1, 144),
        (0, 0),
        (0, 25),
        (0, 725),
        (0, 188),
        (1, 268),
        (0, 944),
        (0, 172),
        (3, 445),
        (0, 132),
        (0, 5),
        (3, 410),
        (1, 63),
        (2, 479),
        (0, 63),
        (0, 1),
        (2, 442),
        (4, 119),
        (0, 0),
        (0, 773),
        (7, 301),
        (10, 785),
        (0, 396),
    ],
    entries: &[
        (".tmcommand", &["XML Property List"]),
        (".js.erb", &["JavaScript+ERB"]),
        (".djs", &["Dogescript"]),
        (".nproj", &["XML"]),
        (".fun", &["Standard ML"]),
        (".pfa", &["PostScript"]),
        (".vhd", &["VHDL"]),
        (".8", &["Roff", "Roff Manpage"]),
        (".self", &["Self"]),
        (".gbl", &["Gerber Image"]),
        (".pkgproj", &["XML"]),
        (".ml4", &["OCaml"]),
        (".libsonnet", &["Jsonnet"]),
        (".xpy", &["Python"]),
        (".yrl", &["Erlang"]),
        (".brd", &["Eagle", "KiCad Legacy Layout"]),
        (".axi", &["NetLinx"]),
        (".lsl", &["LSL"]),
        (".veo", &["Verilog"]),
        (".vhw", &["VHDL"]),
        (".mod", &["Linux Kernel Module", "AMPL", "Modula-2", "XML"]),
        (".hlean", &["Lean"]),
        (".pytb", &["Python traceback"]),
        (".psc", &["Papyrus"]),
        (".textile", &["Textile"]),
        (".pm", &["X PixMap", "Raku", "Perl"]),
        (".fsi", &["F#"]),
        (".pbi", &["PureBasic"]),
        (".pd_lua", &["Lua"]),
        (".ms", &["Roff", "MAXScript", "Unix Assembly"]),
        (".mg", &["Modula-3"]),
        (".nimble", &["Nim"]),
        (".vapi", &["Vala"]),
        (".plx", &["Perl"]),
        (".1in", &["Roff", "Roff Manpage"]),
        (".ox", &["Ox"]),
        (".hta", &["HTA"]),
        (".wsdl", &["XML"]),
        (".pl6", &["Raku"]),
        (".boo", &["Boo"]),
        (".pb", &["PureBasic"]),
        (".ivy", &["XML"]),
        (".c-objdump", &["C-ObjDump"]),
        (".psgi", &["Perl"]),
        (".scpt", &["AppleScript"]),
        (".gml", &["Graph Modeling Language", "Gerber Image", "Game Maker Language", "XML"]),
        (".ur", &["UrWeb"]),
        (".xacro", &["XML"]),
        (".duby", &["Mirah"]),
        (".ch", &["Charity", "xBase"]),
        (".csl", &["XML"]),
        (".gko", &["Gerber Image"]),
        (".cabal", &["Cabal Config"]),
        (".sss", &["SugarSS"]),
        (".pri", &["QMake"]),
        (".obj", &["Wavefront Object"]),
        (".ads", &["Ada"]),
        (".rsc", &["Rascal"]),
        (".pkl", &["Pickle"]),
        (".cjs", &["JavaScript"]),
        (".jbuilder", &["Ruby"]),
        (".asset", &["Unity3D Asset"]),
        (".g4", &["ANTLR"]),
        (".rdoc", &["RDoc"]),
        (".kit", &["Kit"]),
        (".frx", &["VBA"]),
        (".yml", &["YAML"]),
        (".ltx", &["TeX"]),
        (".natvis", &["XML"]),
        (".flux", &["FLUX"]),
        (".patch", &["Diff"]),
        (".pro", &["INI", "Prolog", "Proguard", "IDL", "QMake"]),
        (".csx", &["C#"]),
        (".xlf", &["XML"]),
        (".ash", &["AGS Script"]),
        (".darcspatch", &["Darcs Patch"]),
        (".emberscript", &["EmberScript"]),
        (".h++", &["C++"]),
        ("._ls", &["LiveScript"]),
        (".dwl", &["DataWeave"]),
        (".shproj", &["XML"]),
        (".d", &["DTrace", "Makefile", "D"]),
        (".coffee", &["CoffeeScript"]),
        (".cy", &["Cycript"]),
        (".cpp", &["C++"]),
        (".proto", &["Protocol Buffer"]),
        (".escript", &["Erlang"]),
        (".topojson", &["JSON"]),
        (".adb", &["Ada"]),
        (".gemspec", &["Ruby"]),
        (".outjob", &["Altium Designer"]),
        (".chpl", &["Chapel"]),
        (".proj", &["XML"]),
        (".view.lkml", &["LookML"]),
        (".l", &["PicoLisp", "Roff", "Common Lisp", "Lex"]),
        (".raw", &["Raw token data"]),
        (".apib", &["API Blueprint"]),
        (".tm", &["Tcl"]),
        (".tmlanguage", &["XML Property List"]),
        (".xojo_window", &["Xojo"]),
        (".ex", &["Elixir"]),
        (".v", &["Coq", "Verilog", "V"]),
        (".tmsnippet", &["XML Property List"]),
        (".pot", &["Gettext Catalog"]),
        (".smali", &["Smali"]),
        (".yaml-tmlanguage", &["YAML"]),
        (".rviz", &["YAML"]),
        (".command", &["Shell"]),
        (".druby", &["Mirah"]),
        (".scala", &["Scala"]),
        (".phpt", &["PHP"]),
        (".gsx", &["Gosu"]),
        (".java", &["Java"]),
        (".chs", &["C2hs Haskell"]),
        (".zil", &["ZIL"]),
        (".xht", &["HTML"]),
        (".vho", &["VHDL"]),
        (".ditaval", &["XML"]),
        (".lslp", &["LSL"]),
        (".asy", &["Asymptote", "LTspice Symbol"]),
        (".dpr", &["Pascal"]),
        (".maxhelp", &["Max"]),
        (".rbuistate", &["REALbasic"]),
        (".rhtml", &["RHTML"]),
        (".srt", &["SRecode Template", "SubRip Text"]),
        (".rl", &["Ragel"]),
        (".mo", &["Modelica"]),
        (".jsb", &["JavaScript"]),
        (".rss", &["XML"]),
        (".tesc", &["GLSL"]),
        (".vhost", &["Nginx", "ApacheConf"]),
        (".sl", &["Slash"]),
        (".bzl", &["Starlark"]),
        (".cql", &["SQL"]),
        (".mqh", &["MQL5", "MQL4"]),
        (".cobol", &["COBOL"]),
        (".f90", &["Fortran"]),
        (".lid", &["Dylan"]),
        (".gpb", &["Gerber Image"]),
        (".gvy", &["Groovy"]),
        (".eclass", &["Gentoo Eclass"]),
        (".mud", &["ZIL"]),
        (".cfg", &["INI", "HAProxy"]),
        (".cfm", &["ColdFusion"]),
        (".udo", &["Csound"]),
        (".launch", &["XML"]),
        (".for", &["Forth", "Formatted", "Fortran"]),
        (".ts", &["XML", "TypeScript"]),
        (".xtend", &["Xtend"]),
        (".scxml", &["XML"]),
        (".robot", &["RobotFramework"]),
        (".xsjslib", &["JavaScript"]),
        (".ncl", &["NCL", "Text", "XML"]),
        (".mrc", &["mIRC Script"]),
        (".wxi", &["XML"]),
        (".mly", &["OCaml"]),
        (".schdoc", &["Altium Designer"]),
        (".avsc", &["JSON"]),
        (".conll", &["CoNLL-U"]),
        (".hy", &["Hy"]),
        (".moo", &["Moocode", "Mercury"]),
        (".mq4", &["MQL4"]),
        (".db2", &["SQLPL"]),
        (".sh.in", &["Shell"]),
        (".props", &["XML"]),
        (".mbox", &["EML"]),
        (".vxml", &["XML"]),
        (".cnc", &["G-code"]),
        (".bdy", &["PLSQL"]),
        (".vw", &["PLSQL"]),
        (".xc", &["XC"]),
        (".gto", &["Gerber Image"]),
        (".edn", &["edn"]),
        (".xpl", &["XProc"]),
        (".roff", &["Roff"]),
        (".vtt", &["WebVTT"]),
        (".sublime_metrics", &["JSON with Comments"]),
        (".pat", &["Max"]),
        (".1m", &["Roff", "Roff Manpage"]),
        (".snippets", &["Vim Snippet"]),
        (".gypi", &["Python"]),
        (".1x", &["Roff", "Roff Manpage"]),
        (".rabl", &["Ruby"]),
        (".rd", &["R"]),
        (".awk", &["Awk"]),
        (".abnf", &["ABNF"]),
        (".lmi", &["Python"]),
        (".anim", &["Unity3D Asset"]),
        (".zsh", &["Shell"]),
        (".csh", &["Tcsh"]),
        (".mll", &["OCaml"]),
        (".bones", &["JavaScript"]),
        (".scrbl", &["Racket"]),
        (".cxx-objdump", &["Cpp-ObjDump"]),
        (".el", &["Emacs Lisp"]),
        (".h", &["Objective-C", "C", "C++"]),
        (".qbs", &["QML"]),
        (".rno", &["Roff", "RUNOFF"]),
        (".sublime-syntax", &["YAML"]),
        (".ston", &["STON"]),
        (".dyalog", &["APL"]),
        (".cljs", &["Clojure"]),
        (".desktop", &["desktop"]),
        (".xaml", &["XML"]),
        (".q", &["q", "HiveQL"]),
        (".nim.cfg", &["Nim"]),
        (".gap", &["GAP"]),
        (".mspec", &["Ruby"]),
        (".fish", &["fish"]),
        (".cfc", &["ColdFusion CFC"]),
        (".vsixmanifest", &["XML"]),
        (".pyx", &["Cython"]),
        (".gawk", &["Awk"]),
        (".nc", &["nesC"]),
        (".cob", &["COBOL"]),
        (".doh", &["Stata"]),
        (".zmpl", &["Zimpl"]),
        (".prefs", &["INI"]),
        (".flf", &["FIGlet Font"]),
        (".reg", &["Windows Registry Entries"]),
        (".mxt", &["Max"]),
        (".vhdl", &["VHDL"]),
        (".plsql", &["PLSQL"]),
        (".jisonlex", &["Jison Lex"]),
        (".js", &["JavaScript+URIEncoded", "JavaScript+JSFuck", "JavaScript", "JavaScript+HexString", "JavaScript+Packer", "JavaScript+CharCodeSubtract", "JavaScript+LongIdent", "JavaScript+ObfuscatorIO"]),
        (".gnuplot", &["Gnuplot"]),
        (".god", &["Ruby"]),
        (".tsx", &["TSX", "XML"]),
        (".nsh", &["NSIS"]),
        (".jsp", &["Java Server Pages"]),
        (".http", &["HTTP"]),
        (".wxl", &["XML"]),
        (".mxml", &["XML"]),
        (".asd", &["Common Lisp"]),
        (".ui", &["XML"]),
        (".mkdn", &["Markdown"]),
        (".ksh", &["Shell"]),
        (".model.lkml", &["LookML"]),
        (".oxh", &["Ox"]),
        (".cr", &["Crystal"]),
        (".cps", &["Component Pascal"]),
        ("._coffee", &["CoffeeScript"]),
        (".ndproj", &["XML"]),
        (".nse", &["Lua"]),
        (".muf", &["MUF"]),
        (".afm", &["Adobe Font Metrics"]),
        (".fx", &["HLSL", "FLUX"]),
        (".prg", &["xBase"]),
        (".x", &["RPC", "Logos", "DirectX 3D File", "Linker Script"]),
        (".sed", &["sed"]),
        (".dotsettings", &["XML"]),
        (".ihlp", &["Stata"]),
        (".m4", &["M4Sugar", "M4"]),
        (".vhi", &["VHDL"]),
        (".prisma", &["Prisma"]),
        (".pov", &["POV-Ray SDL"]),
        (".pl", &["Raku", "Prolog", "Perl"]),
        (".dll.config", &["XML"]),
        (".ino", &["C++"]),
        (".logtalk", &["Logtalk"]),
        (".litcoffee", &["Literate CoffeeScript"]),
        (".liquid", &["Liquid"]),
        (".5", &["Roff", "Roff Manpage"]),
        (".hpp", &["C++"]),
        (".ql", &["CodeQL"]),
        (".hs-boot", &["Haskell"]),
        (".vsh", &["GLSL"]),
        (".xsl", &["XSLT"]),
        (".rex", &["REXX"]),
        (".pp", &["Puppet", "Pascal"]),
        (".desktop.in", &["desktop"]),
        (".7", &["Roff", "Roff Manpage"]),
        (".mao", &["Mako"]),
        (".no", &["Text"]),
        (".pug", &["Pug"]),
        (".haml", &["Haml"]),
        (".nu", &["Nu"]),
        (".hqf", &["SQF"]),
        (".fancypack", &["Fancy"]),
        (".asn1", &["ASN.1"]),
        (".hc", &["HolyC"]),
        (".mlir", &["MLIR"]),
        (".jinja2", &["HTML+Django"]),
        (".mk", &["Makefile"]),
        (".sqf", &["SQF"]),
        (".graphql", &["GraphQL"]),
        (".iuml", &["PlantUML"]),
        (".s", &["Motorola 68K Assembly", "Unix Assembly"]),
        (".f77", &["Fortran"]),
        (".cs", &["Smalltalk", "C#"]),
        (".cls", &["Apex", "ObjectScript", "TeX", "OpenEdge ABL", "VBA"]),
        (".sty", &["TeX"]),
        (".pod", &["Pod", "Pod 6"]),
        (".las", &["Lasso"]),
        (".e", &["E", "Eiffel"]),
        (".p8", &["Lua"]),
        (".x68", &["Motorola 68K Assembly"]),
        (".mysql", &["SQL"]),
        (".xproj", &["XML"]),
        (".pd", &["Pure Data"]),
        (".dm", &["DM"]),
        (".xspec", &["XML"]),
        (".opal", &["Opal"]),
        (".vhs", &["VHDL"]),
        (".befunge", &["Befunge"]),
        (".xzap", &["ZAP"]),
        (".gbp", &["Gerber Image"]),
        (".pac", &["JavaScript"]),
        (".bb", &["BitBake", "BlitzBasic"]),
        (".re", &["Reason", "C++"]),
        (".haml.deface", &["Haml"]),
        (".jsonnet", &["Jsonnet"]),
        (".xi", &["Logos"]),
        (".scd", &["SuperCollider"]),
        (".st", &["Smalltalk", "HTML"]),
        (".sls", &["Scheme", "SaltStack"]),
        (".p", &["Gnuplot", "OpenEdge ABL"]),
        (".eye", &["Ruby"]),
        (".pyt", &["Python"]),
        (".gshader", &["GLSL"]),
        (".pde", &["Processing"]),
        (".eex", &["HTML+EEX"]),
        (".sra", &["PowerBuilder"]),
        (".vstemplate", &["XML"]),
        (".ttl", &["Turtle"]),
        (".dcl", &["Clean"]),
        (".mdwn", &["Markdown"]),
        (".rs.in", &["Rust"]),
        (".tcc", &["C++"]),
        (".sublime-workspace", &["JSON with Comments"]),
        (".ssjs", &["JavaScript"]),
        (".vhf", &["VHDL"]),
        (".iced", &["CoffeeScript"]),
        (".ooc", &["ooc"]),
        (".zs", &["ZenScript"]),
        (".ninja", &["Ninja"]),
        (".tfvars", &["HCL"]),
        (".4", &["Roff", "Roff Manpage"]),
        (".gyp", &["Python"]),
        (".bbx", &["TeX"]),
        (".tese", &["GLSL"]),
        (".jelly", &["XML"]),
        (".eq", &["EQ"]),
        (".mt", &["Mathematica"]),
        (".slim", &["Slim"]),
        (".sps", &["Scheme"]),
        (".bas", &["VBA"]),
        (".mir", &["YAML"]),
        (".oxygene", &["Oxygene"]),
        (".c++", &["C++"]),
        (".nb", &["Text", "Mathematica"]),
        (".weechatlog", &["IRC log"]),
        (".1", &["Roff", "Roff Manpage"]),
        (".xm", &["Logos"]),
        (".axs.erb", &["NetLinx+ERB"]),
        (".tmac", &["Roff"]),
        (".phtml", &["HTML+PHP"]),
        (".ld", &["Linker Script"]),
        (".yang", &["YANG"]),
        (".monkey", &["Monkey"]),
        (".lidr", &["Idris"]),
        (".cgi", &["Shell", "Perl", "Python"]),
        (".workbook", &["Markdown"]),
        (".ru", &["Ruby"]),
        (".md", &["GCC Machine Description", "Markdown"]),
        (".ecr", &["HTML+ECR"]),
        (".wxs", &["XML"]),
        (".sparql", &["SPARQL"]),
        (".sublime-theme", &["JSON with Comments"]),
        (".raml", &["RAML"]),
        (".3pm", &["Roff", "Roff Manpage"]),
        (".ecl", &["ECL", "ECLiPSe"]),
        (".kts", &["Kotlin"]),
        (".zone", &["DNS Zone"]),
        (".sma", &["Pawn"]),
        (".flex", &["JFlex"]),
        (".eliom", &["OCaml"]),
        (".rsx", &["R"]),
        (".sql", &["TSQL", "SQL", "PLSQL", "PLpgSQL", "SQLPL"]),
        (".fr", &["Forth", "Frege", "Text"]),
        (".asciidoc", &["AsciiDoc"]),
        (".pub", &["Public Key"]),
        (".xq", &["XQuery"]),
        (".vht", &["VHDL"]),
        (".3", &["Roff", "Roff Manpage"]),
        (".cljc", &["Clojure"]),
        (".click", &["Click"]),
        (".sthlp", &["Stata"]),
        (".snip", &["Vim Snippet"]),
        (".prc", &["SQL", "PLSQL"]),
        (".webapp", &["JSON"]),
        (".xsp-config", &["XPages"]),
        (".mli", &["OCaml"]),
        (".do", &["Stata"]),
        (".ccxml", &["XML"]),
        (".latte", &["Latte"]),
        (".pkb", &["PLSQL"]),
        (".cdf", &["Mathematica"]),
        (".pyw", &["Python"]),
        (".reds", &["Red"]),
        (".gitconfig", &["Git Config"]),
        (".monkey2", &["Monkey"]),
        (".xpm", &["X PixMap"]),
        (".aw", &["PHP"]),
        (".a51", &["Assembly"]),
        (".sco", &["Csound Score"]),
        (".plot", &["Gnuplot"]),
        (".dtx", &["TeX"]),
        (".dot", &["Graphviz (DOT)"]),
        (".sh", &["Shell"]),
        (".pgsql", &["PLpgSQL"]),
        (".sage", &["Sage"]),
        (".builder", &["Ruby"]),
        (".webmanifest", &["JSON"]),
        (".dockerfile", &["Dockerfile"]),
        (".wlk", &["Wollok"]),
        (".sld", &["Scheme"]),
        (".pyi", &["Python"]),
        (".mu", &["mupad"]),
        (".sublime-settings", &["JSON with Comments"]),
        (".tmtheme", &["XML Property List"]),
        (".filters", &["XML"]),
        (".mkd", &["Markdown"]),
        (".emacs", &["Emacs Lisp"]),
        (".scad", &["OpenSCAD"]),
        (".vbproj", &["XML"]),
        (".angelscript", &["AngelScript"]),
        (".cbx", &["TeX"]),
        (".ml", &["Standard ML", "OCaml"]),
        (".epsi", &["PostScript"]),
        (".pogo", &["PogoScript"]),
        (".erl", &["Erlang"]),
        (".admx", &["XML"]),
        (".clixml", &["XML"]),
        (".puml", &["PlantUML"]),
        (".es6", &["JavaScript"]),
        (".diff", &["Diff"]),
        (".bdf", &["Glyph Bitmap Distribution Format"]),
        (".cbl", &["COBOL"]),
        (".cuh", &["Cuda"]),
        (".nims", &["Nim"]),
        (".kicad_mod", &["KiCad Layout"]),
        (".ps1", &["PowerShell"]),
        (".gpt", &["Gerber Image"]),
        (".nit", &["Nit"]),
        (".inc", &["Assembly", "SourcePawn", "Motorola 68K Assembly", "Pawn", "SQL", "Pascal", "NASL", "PHP", "POV-Ray SDL", "HTML", "C++"]),
        (".iml", &["XML"]),
        (".depproj", &["XML"]),
        (".sexp", &["Common Lisp"]),
        (".clw", &["Clarion"]),
        (".cake", &["CoffeeScript", "C#"]),
        (".3m", &["Roff", "Roff Manpage"]),
        (".xojo_menu", &["Xojo"]),
        (".ps1xml", &["XML"]),
        (".php5", &["PHP"]),
        (".elm", &["Elm"]),
        (".rst.txt", &["reStructuredText"]),
        (".nasl", &["NASL"]),
        (".ipynb", &["Jupyter Notebook"]),
        (".scm", &["Scheme"]),
        (".dats", &["ATS"]),
        (".rktl", &["Racket"]),
        (".json-tmlanguage", &["JSON"]),
        (".xsjs", &["JavaScript"]),
        (".fpp", &["Fortran"]),
        (".lagda", &["Literate Agda"]),
        (".grace", &["Grace"]),
        (".vbhtml", &["Visual Basic .NET"]),
        (".gradle", &["Gradle"]),
        (".9", &["Roff", "Roff Manpage"]),
        (".mkvi", &["TeX"]),
        (".bibtex", &["BibTeX"]),
        (".bats", &["Shell"]),
        (".sublime-commands", &["JSON with Comments"]),
        (".apacheconf", &["ApacheConf"]),
        (".upc", &["Unified Parallel C"]),
        (".pbt", &["PowerBuilder"]),
        (".ph", &["Perl"]),
        (".grt", &["Groovy"]),
        (".rake", &["Ruby"]),
        (".targets", &["XML"]),
        (".vshader", &["GLSL"]),
        (".kt", &["Kotlin"]),
        (".plist", &["OpenStep Property List", "XML Property List"]),
        (".ccproj", &["XML"]),
        (".decls", &["BlitzBasic"]),
        (".pprx", &["REXX"]),
        (".sce", &["Scilab"]),
        (".capnp", &["Cap'n Proto"]),
        (".hlsl", &["HLSL"]),
        (".8xk", &["TI Program"]),
        (".rockspec", &["Lua"]),
        (".fxh", &["HLSL"]),
        (".plantuml", &["PlantUML"]),
        (".asm", &["Assembly", "Motorola 68K Assembly"]),
        (".perl", &["Perl"]),
        (".au3", &["AutoIt"]),
        (".vh", &["SystemVerilog"]),
        (".xmi", &["XML"]),
        (".nlogo", &["NetLogo"]),
        (".shader", &["ShaderLab", "GLSL"]),
        (".syntax", &["YAML"]),
        (".feature", &["Gherkin"]),
        (".fy", &["Fancy"]),
        (".psc1", &["XML"]),
        (".chem", &["Pic"]),
        (".nimrod", &["Nim"]),
        (".maxpat", &["Max"]),
        (".fth", &["Forth"]),
        (".bal", &["Ballerina"]),
        (".xojo_report", &["Xojo"]),
        (".intr", &["Dylan"]),
        ("._js", &["JavaScript"]),
        (".jss", &["JavaScript"]),
        (".glslv", &["GLSL"]),
        (".vcxproj", &["XML"]),
        (".cc", &["C++"]),
        (".htm", &["HTML"]),
        (".factor", &["Factor"]),
        (".pod6", &["Pod 6"]),
        (".lhs", &["Literate Haskell"]),
        (".tl", &["Type Language"]),
        (".fea", &["OpenType Feature File"]),
        (".mmk", &["Module Management System"]),
        (".sc", &["Scala", "SuperCollider"]),
        (".n", &["Roff", "Nemerle"]),
        (".hic", &["Clojure"]),
        (".inl", &["C++"]),
        (".meta", &["Unity3D Asset"]),
        (".i", &["Assembly", "Motorola 68K Assembly", "SWIG"]),
        (".axd", &["ASP"]),
        (".gnu", &["Gnuplot"]),
        (".lsp", &["Common Lisp", "NewLisp"]),
        (".mss", &["CartoCSS"]),
        (".xql", &["XQuery"]),
        (".sublime_session", &["JSON with Comments"]),
        (".fst", &["F*"]),
        (".ampl", &["AMPL"]),
        (".prolog", &["Prolog"]),
        (".scss", &["SCSS"]),
        (".wlt", &["Mathematica"]),
        (".pwn", &["Pawn"]),
        (".mirah", &["Mirah"]),
        (".dsp", &["Microsoft Developer Studio Project", "Faust"]),
        (".twig", &["Twig"]),
        (".jsonc", &["JSON with Comments"]),
        (".lpr", &["Pascal"]),
        (".8xp", &["TI Program"]),
        (".gi", &["GAP"]),
        (".pan", &["Pan"]),
        (".tcl", &["Tcl"]),
        (".cfml", &["ColdFusion"]),
        (".rebol", &["Rebol"]),
        (".thrift", &["Thrift"]),
        (".mq5", &["MQL5"]),
        (".markdown", &["Markdown"]),
        (".aspx", &["ASP"]),
        (".ly", &["LilyPond"]),
        (".jq", &["JSONiq"]),
        (".pmod", &["Pike"]),
        (".3qt", &["Roff", "Roff Manpage"]),
        (".properties", &["INI", "Java Properties"]),
        (".srdf", &["XML"]),
        (".vssettings", &["XML"]),
        (".ado", &["Stata"]),
        (".myt", &["Myghty"]),
        (".ipp", &["C++"]),
        (".apl", &["APL"]),
        (".nasm", &["Assembly"]),
        (".ahkl", &["AutoHotkey"]),
        (".nginxconf", &["Nginx"]),
        (".nr", &["Roff"]),
        (".mediawiki", &["MediaWiki"]),
        (".vala", &["Vala"]),
        (".snippet", &["Vim Snippet"]),
        (".gaml", &["GAML"]),
        (".prw", &["xBase"]),
        (".riot", &["Riot"]),
        (".tab", &["SQL"]),
        (".erb.deface", &["HTML+ERB"]),
        (".abap", &["ABAP"]),
        (".pir", &["Parrot Internal Representation"]),
        (".txi", &["Texinfo"]),
        (".swift", &["Swift"]),
        (".smt2", &["SMT"]),
        (".nanorc", &["nanorc"]),
        (".lasso9", &["Lasso"]),
        (".tpb", &["PLSQL"]),
        (".spc", &["PLSQL"]),
        (".mtl", &["Wavefront Material"]),
        (".bro", &["Zeek"]),
        (".geo", &["GLSL"]),
        (".sublime-macro", &["JSON with Comments"]),
        (".jinja", &["HTML+Django"]),
        (".njk", &["HTML+Django"]),
        (".gql", &["GraphQL"]),
        (".em", &["EmberScript"]),
        (".ada", &["Ada"]),
        (".aj", &["AspectJ"]),
        (".erb", &["HTML+ERB"]),
        (".com", &["DIGITAL Command Language"]),
        (".mcfunction", &["mcfunction"]),
        (".ni", &["Inform 7"]),
        (".xbm", &["X BitMap"]),
        (".rmd", &["RMarkdown"]),
        (".cljscm", &["Clojure"]),
        (".php", &["Hack", "PHP"]),
        (".rbi", &["Ruby"]),
        (".mcmeta", &["JSON"]),
        (".rktd", &["Racket"]),
        (".frt", &["Forth"]),
        (".sass", &["Sass"]),
        (".wisp", &["wisp"]),
        (".sas", &["SAS"]),
        (".wlua", &["Lua"]),
        (".red", &["Red"]),
        (".sats", &["ATS"]),
        (".cscfg", &["XML"]),
        (".cu", &["Cuda"]),
        (".yara", &["YARA"]),
        (".regex", &["Regular Expression"]),
        (".ashx", &["ASP"]),
        (".gts", &["Gerber Image"]),
        (".mdx", &["Markdown"]),
        (".adml", &["XML"]),
        (".ls", &["LiveScript", "LoomScript"]),
        (".gmx", &["XML"]),
        (".mcr", &["MAXScript"]),
        (".rbw", &["Ruby"]),
        (".lgt", &["Logtalk"]),
        (".lasso", &["Lasso"]),
        (".sublime-completions", &["JSON with Comments"]),
        (".rbuild", &["Ruby"]),
        (".xul", &["XML"]),
        (".asn", &["ASN.1"]),
        (".axi.erb", &["NetLinx+ERB"]),
        (".mask", &["Unity3D Asset", "Mask"]),
        (".xsd", &["XML"]),
        (".sublime-project", &["JSON with Comments"]),
        (".fp", &["GLSL"]),
        (".ux", &["XML"]),
        (".gv", &["Graphviz (DOT)"]),
        (".rbres", &["REALbasic"]),
        (".qml", &["QML"]),
        (".coq", &["Coq"]),
        (".dae", &["COLLADA"]),
        (".matah", &["Stata"]),
        (".xliff", &["XML"]),
        (".pep", &["Pep8"]),
        (".lfe", &["LFE"]),
        (".arpa", &["DNS Zone"]),
        (".odin", &["Object Data Instance Notation", "Odin"]),
        (".f", &["Forth", "Filebench WML", "Fortran"]),
        (".prjpcb", &["Altium Designer"]),
        (".txl", &["TXL"]),
        (".ronn", &["Markdown"]),
        (".nawk", &["Awk"]),
        (".sublime-menu", &["JSON with Comments"]),
        (".svelte", &["Svelte"]),
        (".psd1", &["PowerShell"]),
        (".rbx", &["Ruby"]),
        (".srw", &["PowerBuilder"]),
        (".podsl", &["Common Lisp"]),
        (".scaml", &["Scaml"]),
        (".gtpl", &["Groovy"]),
        (".orc", &["Csound"]),
        (".dita", &["XML"]),
        (".cson", &["CSON"]),
        (".yar", &["YARA"]),
        (".j", &["Objective-J", "Jasmin"]),
        (".kicad_wks", &["KiCad Layout"]),
        (".tac", &["Python"]),
        (".oxo", &["Ox"]),
        (".f08", &["Fortran"]),
        (".ddl", &["SQL", "PLSQL"]),
        (".lbx", &["TeX"]),
        (".eam.fs", &["Formatted"]),
        (".sch", &["Eagle", "Scheme", "KiCad Schematic", "XML"]),
        (".os", &["1C Enterprise"]),
        (".tml", &["XML"]),
        (".eb", &["Easybuild"]),
        (".sbt", &["Scala"]),
        (".opencl", &["OpenCL"]),
        (".cw", &["Redcode"]),
        (".rei", &["Reason"]),
        (".glsl", &["GLSL"]),
        (".fshader", &["GLSL"]),
        (".eml", &["EML"]),
        (".es", &["JavaScript", "Erlang"]),
        (".py3", &["Python"]),
        (".lookml", &["LookML"]),
        (".sublime-keymap", &["JSON with Comments"]),
        (".fsproj", &["XML"]),
        (".mm", &["Objective-C++", "XML"]),
        (".r", &["Rebol", "R"]),
        (".sublime-snippet", &["XML"]),
        (".cjsx", &["CoffeeScript"]),
        (".yml.mysql", &["YAML"]),
        (".xhtml", &["HTML"]),
        (".vbs", &["VBScript", "VBScript+HTMLDecoy"]),
        (".f95", &["Fortran"]),
        (".ss", &["Scheme"]),
        (".ctp", &["PHP"]),
        (".cginc", &["HLSL"]),
        (".3p", &["Roff", "Roff Manpage"]),
        (".zcml", &["XML"]),
        (".csd", &["Csound Document"]),
        (".mdown", &["Markdown"]),
        (".lisp", &["Common Lisp", "NewLisp"]),
        (".ck", &["ChucK"]),
        (".postcss", &["PostCSS"]),
        (".hcl", &["HCL"]),
        (".spec", &["RPM Spec", "Python", "Ruby"]),
        (".p6m", &["Raku"]),
        (".creole", &["Creole"]),
        (".tst", &["Scilab", "GAP"]),
        (".vrx", &["GLSL"]),
        (".unity", &["Unity3D Asset"]),
        (".lol", &["LOLCODE"]),
        (".workflow", &["HCL", "XML"]),
        (".html", &["HTML"]),
        (".html.hl", &["HTML"]),
        (".t", &["Raku", "Perl", "Terra", "Turing"]),
        (".gms", &["GAMS"]),
        (".ebuild", &["Gentoo Ebuild"]),
        (".stan", &["Stan"]),
        (".d-objdump", &["D-ObjDump"]),
        (".cppobjdump", &["Cpp-ObjDump"]),
        (".3x", &["Roff", "Roff Manpage"]),
        (".man", &["Roff", "Roff Manpage"]),
        (".icl", &["Clean"]),
        (".svg", &["SVG"]),
        (".yy", &["JSON", "Yacc"]),
        (".tea", &["Tea"]),
        (".sh-session", &["ShellSession"]),
        (".dpatch", &["Darcs Patch"]),
        (".cshtml", &["HTML+Razor"]),
        (".cl2", &["Clojure"]),
        (".mak", &["Makefile"]),
        (".c++-objdump", &["Cpp-ObjDump"]),
        (".gbo", &["Gerber Image"]),
        (".aug", &["Augeas"]),
        (".gf", &["Grammatical Framework"]),
        (".bat", &["Batchfile", "Batchfile+CaretObfuscated"]),
        (".mata", &["Stata"]),
        (".hb", &["Harbour"]),
        (".kojo", &["Scala"]),
        (".csdef", &["XML"]),
        (".jade", &["Pug"]),
        (".vark", &["Gosu"]),
        (".ruby", &["Ruby"]),
        (".plt", &["Gnuplot"]),
        (".sfd", &["Spline Font Database"]),
        (".6", &["Roff", "Roff Manpage"]),
        (".lektorproject", &["INI"]),
        (".xs", &["XS"]),
        (".pyde", &["Python"]),
        (".vba", &["Vim script", "VBA+JSONPacked", "VBA"]),
        (".yasnippet", &["YASnippet"]),
        (".adp", &["Tcl"]),
        (".ejs", &["EJS"]),
        (".glslf", &["GLSL"]),
        (".matlab", &["MATLAB"]),
        (".xib", &["XML"]),
        (".iss", &["Inno Setup"]),
        (".numpy", &["NumPy"]),
        (".texinfo", &["Texinfo"]),
        (".glade", &["XML"]),
        (".pyp", &["Python"]),
        (".cpy", &["COBOL"]),
        (".smk", &["Python"]),
        (".pm6", &["Raku"]),
        (".b", &["Brainfuck", "Limbo"]),
        (".dart", &["Dart"]),
        (".fcgi", &["Shell", "Perl", "Python", "PHP", "Ruby", "Lua"]),
        (".fxml", &["XML"]),
        (".mat", &["Unity3D Asset"]),
        (".sjs", &["JavaScript"]),
        (".pasm", &["Parrot Assembly"]),
        (".bmx", &["BlitzMax"]),
        (".groovy", &["Groovy"]),
        (".hats", &["ATS"]),
        (".nl", &["NL", "NewLisp"]),
        (".m", &["Objective-C", "Mercury", "M", "MUF", "MATLAB", "Limbo", "Mathematica"]),
        (".cproject", &["XML"]),
        (".rs", &["Rust", "RenderScript"]),
        (".dof", &["INI"]),
        (".zep", &["Zephir"]),
        (".jscad", &["JavaScript"]),
        (".zeek", &["Zeek"]),
        (".gst", &["Gosu"]),
        (".parrot", &["Parrot"]),
        (".blade", &["Blade"]),
        (".fnc", &["PLSQL"]),
        (".webidl", &["WebIDL"]),
        (".fsx", &["F#"]),
        (".shen", &["Shen"]),
        (".go", &["Go"]),
        (".gcode", &["G-code"]),
        (".org", &["Org"]),
        (".zpl", &["Zimpl"]),
        (".xojo_toolbar", &["Xojo"]),
        (".mkii", &["TeX"]),
        (".gn", &["GN"]),
        (".nsi", &["NSIS"]),
        (".builds", &["XML"]),
        (".rnh", &["RUNOFF"]),
        (".nbp", &["Mathematica"]),
        (".6pm", &["Raku"]),
        (".pluginspec", &["Ruby", "XML"]),
        (".blade.php", &["Blade"]),
        (".svh", &["SystemVerilog"]),
        (".cwl", &["Common Workflow Language"]),
        (".pck", &["PLSQL"]),
        (".spin", &["Propeller Spin"]),
        (".sublime-mousemap", &["JSON with Comments"]),
        (".oz", &["Oz"]),
        (".prefab", &["Unity3D Asset"]),
        (".lds", &["Linker Script"]),
        (".mathematica", &["Mathematica"]),
        (".sublime-build", &["JSON with Comments"]),
        (".csproj", &["XML"]),
        (".wat", &["WebAssembly"]),
        (".sci", &["Scilab"]),
        (".gdbinit", &["GDB"]),
        (".tf", &["HCL"]),
        (".mtml", &["MTML"]),
        (".sp", &["SourcePawn"]),
        (".har", &["JSON"]),
        (".gp", &["Gnuplot"]),
        (".watchr", &["Ruby"]),
        (".tool", &["Shell"]),
        (".gco", &["G-code"]),
        (".x10", &["X10"]),
        (".cmd", &["Batchfile", "Batchfile+CaretObfuscated"]),
        (".ditamap", &["XML"]),
        (".tfstate", &["JSON"]),
        (".objdump", &["ObjDump"]),
        (".podspec", &["Ruby"]),
        (".ebnf", &["EBNF"]),
        (".tcsh", &["Tcsh"]),
        (".c", &["C"]),
        (".ct", &["XML"]),
        (".di", &["D"]),
        (".wiki", &["MediaWiki"]),
        (".glf", &["Glyph"]),
        (".mdpolicy", &["XML"]),
        (".bsv", &["Bluespec"]),
        (".make", &["Makefile"]),
        (".idr", &["Idris"]),
        (".tpp", &["C++"]),
        (".gtl", &["Gerber Image"]),
        (".osm", &["XML"]),
        (".nim", &["Nim"]),
        (".ll", &["LLVM"]),
        (".hh", &["Hack", "C++"]),
        (".rest", &["reStructuredText"]),
        (".gbs", &["Gerber Image"]),
        (".ant", &["XML"]),
        (".mdoc", &["Roff", "Roff Manpage"]),
        (".pic", &["Pic"]),
        (".axml", &["XML"]),
        (".g", &["G-code", "GAP"]),
        (".ps", &["PostScript"]),
        (".xslt", &["XSLT"]),
        (".rbmnu", &["REALbasic"]),
        (".geojson", &["JSON"]),
        (".bison", &["Bison"]),
        (".tex", &["TeX"]),
        (".8xp.txt", &["TI Program"]),
        (".json5", &["JSON5"]),
        (".pas", &["Pascal"]),
        (".idc", &["C"]),
        (".cats", &["C"]),
        (".gltf", &["JSON"]),
        (".urs", &["UrWeb"]),
        (".yacc", &["Yacc"]),
        (".rbxs", &["Lua"]),
        (".ascx", &["ASP"]),
        (".axs", &["NetLinx"]),
        (".php4", &["PHP"]),
        (".rtf", &["Rich Text Format"]),
        (".clp", &["CLIPS"]),
        (".jison", &["Jison"]),
        (".sig", &["Standard ML"]),
        (".fan", &["Fantom"]),
        (".cmake", &["CMake"]),
        (".pcss", &["PostCSS"]),
        (".wixproj", &["XML"]),
        (".mako", &["Mako"]),
        (".gdb", &["GDB"]),
        (".mustache", &["HTML+Django"]),
        (".clj", &["Clojure"]),
        (".forth", &["Forth"]),
        (".zimpl", &["Zimpl"]),
        (".sttheme", &["XML Property List"]),
        (".xojo_code", &["Xojo"]),
        (".i7x", &["Inform 7"]),
        (".x3d", &["XML"]),
        (".mkiv", &["TeX"]),
        (".ice", &["Slice", "JSON"]),
        (".eclxml", &["ECL"]),
        (".metal", &["Metal"]),
        (".xproc", &["XProc"]),
        (".xqm", &["XQuery"]),
        (".io", &["Io"]),
        (".y", &["Yacc"]),
        (".dircolors", &["dircolors"]),
        (".jsx", &["JSX"]),
        (".ne", &["Nearley"]),
        (".sagews", &["Sage"]),
        (".omgrofl", &["Omgrofl"]),
        (".conllu", &["CoNLL-U"]),
        (".agda", &["Agda"]),
        (".vue", &["Vue"]),
        (".gitignore", &["Ignore List"]),
        (".ini", &["INI"]),
        (".reek", &["YAML"]),
        (".uno", &["Uno"]),
        (".cirru", &["Cirru"]),
        (".hhi", &["Hack"]),
        (".jl", &["Julia"]),
        (".sj", &["Objective-J"]),
        (".thor", &["Ruby"]),
        (".pcbdoc", &["Altium Designer"]),
        (".zap", &["ZAP"]),
        (".rbfrm", &["REALbasic"]),
        (".f03", &["Fortran"]),
        (".eps", &["PostScript"]),
        (".lean", &["Lean"]),
        (".dyl", &["Dylan"]),
        (".storyboard", &["XML"]),
        (".iol", &["Jolie"]),
        (".dhall", &["Dhall"]),
        (".adoc", &["AsciiDoc"]),
        (".kml", &["XML"]),
        (".sv", &["SystemVerilog"]),
        (".nqp", &["Raku"]),
        (".frag", &["JavaScript", "GLSL"]),
        (".nut", &["Squirrel"]),
        (".mms", &["Module Management System"]),
        (".tfstate.backup", &["JSON"]),
        (".xsp.metadata", &["XPages"]),
        (".razor", &["HTML+Razor"]),
        (".epj", &["Ecere Projects"]),
        (".r3", &["Rebol"]),
        (".ring", &["Ring"]),
        (".ny", &["Common Lisp"]),
        (".gbr", &["Gerber Image"]),
        (".me", &["Roff"]),
        (".pig", &["PigLatin"]),
        (".rbbas", &["REALbasic"]),
        (".pike", &["Pike"]),
        (".p4", &["P4"]),
        (".rexx", &["REXX"]),
        (".tps", &["PLSQL"]),
        (".rbtbar", &["REALbasic"]),
        (".fsh", &["GLSL"]),
        (".gs", &["JavaScript", "Genie", "Gosu", "GLSL"]),
        (".txt", &["Text"]),
        (".vim", &["Vim script"]),
        (".hs", &["Haskell"]),
        (".golo", &["Golo"]),
        (".asax", &["ASP"]),
        (".auk", &["Awk"]),
        (".toml", &["TOML"]),
        (".asp", &["ASP"]),
        (".zig", &["Zig"]),
        (".hxsl", &["Haxe"]),
        (".ma", &["Mathematica"]),
        (".rpy", &["Ren'Py", "Python"]),
        (".as", &["AngelScript", "ActionScript"]),
        (".dlm", &["IDL"]),
        (".p6l", &["Raku"]),
        (".r2", &["Rebol"]),
        (".wl", &["Mathematica"]),
        (".app.src", &["Erlang"]),
        (".json", &["JSON"]),
        (".brs", &["Brightscript"]),
        (".xqy", &["XQuery"]),
        (".bf", &["Brainfuck", "HyPhy"]),
        (".less", &["Less"]),
        (".kid", &["Genshi"]),
        (".gni", &["GN"]),
        (".6pl", &["Raku"]),
        (".csv", &["CSV"]),
        (".pxd", &["Cython"]),
        (".asmx", &["ASP"]),
        (".rdf", &["XML"]),
        (".4dm", &["4D"]),
        (".jsfl", &["JavaScript"]),
        (".ijs", &["J"]),
        (".ik", &["Ioke"]),
        (".rkt", &["Racket"]),
        (".jake", &["JavaScript"]),
        (".edc", &["Edje Data Collection"]),
        (".owl", &["Web Ontology Language"]),
        (".2", &["Roff", "Roff Manpage"]),
        (".xml.dist", &["XML"]),
        (".urdf", &["XML"]),
        (".mkdown", &["Markdown"]),
        (".wsf", &["XML"]),
        (".rb", &["Ruby"]),
        (".hql", &["HiveQL"]),
        (".graphqls", &["GraphQL"]),
        (".xml", &["XML"]),
        (".sfproj", &["XML"]),
        (".jsm", &["JavaScript"]),
        (".po", &["Gettext Catalog"]),
        (".rq", &["SPARQL"]),
        (".yap", &["Prolog"]),
        (".ccp", &["COBOL"]),
        (".mjml", &["XML"]),
        (".styl", &["Stylus"]),
        (".jsonld", &["JSONLD"]),
        (".cljx", &["Clojure"]),
        (".vb", &["Visual Basic .NET"]),
        (".grxml", &["XML"]),
        (".cmake.in", &["CMake"]),
        (".lex", &["Lex"]),
        (".psm1", &["PowerShell"]),
        (".marko", &["Marko"]),
        (".numsc", &["NumPy"]),
        (".eliomi", &["OCaml"]),
        (".rg", &["Rouge"]),
        (".nuspec", &["XML"]),
        (".hack", &["Hack"]),
        (".tmpreferences", &["XML Property List"]),
        (".lua", &["Lua"]),
        (".bib", &["BibTeX"]),
        (".tla", &["TLA"]),
        (".css", &["CSS"]),
        (".pascal", &["Pascal"]),
        (".qasm", &["OpenQASM"]),
        (".soy", &["Closure Templates"]),
        (".c++objdump", &["Cpp-ObjDump"]),
        (".yyp", &["JSON"]),
        (".hlsli", &["HLSL"]),
        (".wdl", &["wdl"]),
        (".thy", &["Isabelle"]),
        (".py", &["Python"]),
        (".ahk", &["AutoHotkey"]),
        (".mkfile", &["Makefile"]),
        (".4th", &["Forth"]),
        (".hx", &["Haxe"]),
        (".trg", &["PLSQL"]),
        (".xrl", &["Erlang"]),
        (".plb", &["PLSQL"]),
        (".php3", &["PHP"]),
        (".odd", &["XML"]),
        (".frm", &["VBA"]),
        (".njs", &["JavaScript"]),
        (".agc", &["Apollo Guidance Computer"]),
        (".jsproj", &["XML"]),
        (".hxx", &["C++"]),
        (".tmux", &["Shell"]),
        (".viw", &["SQL"]),
        (".cp", &["Component Pascal", "C++"]),
        (".nf", &["Nextflow"]),
        (".8xk.txt", &["TI Program"]),
        (".pls", &["PLSQL"]),
        (".phps", &["PHP"]),
        (".mumps", &["M"]),
        (".cl", &["Common Lisp", "Cool", "OpenCL"]),
        (".3in", &["Roff", "Roff Manpage"]),
        (".applescript", &["AppleScript"]),
        (".ily", &["LilyPond"]),
        (".bsl", &["1C Enterprise"]),
        (".eh", &["eC"]),
        (".cocci", &["SmPL"]),
        (".lvproj", &["LabVIEW"]),
        (".ipf", &["IGOR Pro"]),
        (".wsgi", &["Python"]),
        (".toc", &["TeX", "World of Warcraft Addon Data"]),
        (".regexp", &["Regular Expression"]),
        (".rego", &["Open Policy Agent"]),
        (".yaml.sed", &["YAML"]),
        (".irclog", &["IRC log"]),
        (".dylan", &["Dylan"]),
        (".gtp", &["Gerber Image"]),
        (".hsc", &["Haskell"]),
        (".ftl", &["FreeMarker"]),
        (".w", &["CWeb", "OpenEdge ABL"]),
        (".mjs", &["JavaScript"]),
        (".sml", &["Standard ML"]),
        (".als", &["Alloy"]),
        (".arc", &["Arc"]),
        (".muse", &["Muse"]),
        (".ig", &["Modula-3"]),
        (".exs", &["Elixir"]),
        (".ec", &["eC"]),
        (".geom", &["GLSL"]),
        (".emacs.desktop", &["Emacs Lisp"]),
        (".opa", &["Opa"]),
        (".nearley", &["Nearley"]),
        (".m3", &["Modula-3"]),
        (".rsh", &["RenderScript"]),
        (".tu", &["Turing"]),
        (".cljs.hl", &["Clojure"]),
        (".qll", &["CodeQL"]),
        (".uc", &["UnrealScript"]),
        (".fs", &["Forth", "Filterscript", "F#", "GLSL"]),
        (".cpp-objdump", &["Cpp-ObjDump"]),
        (".rst", &["reStructuredText"]),
        (".aux", &["TeX"]),
        (".rest.txt", &["reStructuredText"]),
        (".minid", &["MiniD"]),
        (".jsonl", &["JSON"]),
        (".p6", &["Raku"]),
        (".nix", &["Nix"]),
        (".sru", &["PowerBuilder"]),
        (".vert", &["GLSL"]),
        (".frg", &["GLSL"]),
        (".i3", &["Modula-3"]),
        (".tpl", &["Smarty"]),
        (".pxi", &["Cython"]),
        (".ceylon", &["Ceylon"]),
        (".vmb", &["Vim script"]),
        (".yaml", &["YAML"]),
        (".maxproj", &["Max"]),
        (".reb", &["Rebol"]),
        (".al", &["Perl"]),
        (".wast", &["WebAssembly"]),
        (".gd", &["GDScript", "GAP"]),
        (".cxx", &["C++"]),
        (".lasso8", &["Lasso"]),
        (".ol", &["Jolie"]),
        (".kicad_pcb", &["KiCad Layout"]),
        (".hrl", &["Erlang"]),
        (".ins", &["TeX"]),
        (".ktm", &["Kotlin"]),
        (".resx", &["XML"]),
        (".texi", &["Texinfo"]),
        (".volt", &["Volt"]),
        (".dfm", &["Pascal"]),
        (".jflex", &["JFlex"]),
        (".vcl", &["VCL"]),
        (".bash", &["Shell"]),
        (".pt", &["XML"]),
        (".mawk", &["Awk"]),
        (".hxml", &["HXML"]),
        (".udf", &["SQL"]),
        (".moon", &["MoonScript"]),
        (".smt", &["SMT"]),
        (".pony", &["Pony"]),
        (".xquery", &["XQuery"]),
        (".pks", &["PLSQL"]),
        (".krl", &["KRL"]),
        (".asc", &["Public Key", "AsciiDoc", "AGS Script"]),
        (".numpyw", &["NumPy"]),
        (".purs", &["PureScript"]),
        (".boot", &["Clojure"]),
        (".xojo_script", &["Xojo"]),
    ],
};

