static LANGUAGE_INFO: phf::Map<&'static str, Language> =
::phf::Map {
    key: 12913932095322966823,
    disps: &[
        (0, 0),
        (0, 64),
        (0, 4),
        (0, 73),
        (1, 13),
        (0, 1),
        (0, 3),
        (0, 15),
        (0, 19),
        (0, 68),
        (0, 31),
        (1, 527),
        (0, 5),
        (1, 166),
        (0, 37),
        (11, 291),
        (0, 37),
        (0, 24),
        (0, 145),
        (0, 16),
        (1, 1),
        (0, 0),
        (1, 177),
        (0, 199),
        (8, 445),
        (0, 147),
        (0, 16),
        (0, 490),
        (0, 31),
        (0, 22),
        (0, 528),
        (11, 298),
        (0, 102),
        (0, 5),
        (0, 555),
        (0, 1),
        (0, 10),
        (0, 0),
        (0, 14),
        (10, 327),
        (0, 16),
        (0, 3),
        (0, 47),
        (0, 296),
        (0, 0),
        (0, 363),
        (2, 292),
        (0, 206),
        (0, 9),
        (3, 85),
        (0, 521),
        (0, 3),
        (0, 183),
        (0, 1),
        (8, 117),
        (3, 199),
        (0, 0),
        (0, 7),
        (0, 0),
        (0, 239),
        (1, 219),
        (4, 243),
        (2, 152),
        (0, 1),
        (0, 2),
        (0, 13),
        (0, 175),
        (0, 96),
        (0, 0),
        (0, 65),
        (9, 113),
        (0, 0),
        (1, 23),
        (0, 0),
        (0, 1),
        (0, 8),
        (0, 557),
        (16, 411),
        (128, 449),
        (0, 404),
        (0, 65),
        (16, 388),
        (0, 8),
        (0, 5),
        (0, 4),
        (0, 103),
        (33, 312),
        (0, 358),
        (1, 317),
        (0, 3),
        (0, 4),
        (0, 77),
        (0, 14),
        (0, 152),
        (0, 419),
        (0, 58),
        (48, 261),
        (0, 16),
        (0, 39),
        (0, 0),
        (2, 20),
        (3, 279),
        (0, 2),
        (0, 0),
        (0, 448),
        (0, 46),
        (1, 461),
        (3, 74),
        (4, 141),
        (0, 5),
        (0, 9),
        (27, 270),
    ],
    entries: &[
        ("Rouge", Language { name: "Rouge", language_type: LanguageType::Programming, color: Some("#cc0088"), group: None }),
        ("RobotFramework", Language { name: "RobotFramework", language_type: LanguageType::Programming, color: None, group: None }),
        ("Objective-C", Language { name: "Objective-C", language_type: LanguageType::Programming, color: Some("#438eff"), group: None }),
        ("Gosu", Language { name: "Gosu", language_type: LanguageType::Programming, color: Some("#82937f"), group: None }),
        ("SAS", Language { name: "SAS", language_type: LanguageType::Programming, color: Some("#B34936"), group: None }),
        ("DM", Language { name: "DM", language_type: LanguageType::Programming, color: Some("#447265"), group: None }),
        ("CartoCSS", Language { name: "CartoCSS", language_type: LanguageType::Programming, color: None, group: None }),
        ("GDB", Language { name: "GDB", language_type: LanguageType::Programming, color: None, group: None }),
        ("Brainfuck", Language { name: "Brainfuck", language_type: LanguageType::Programming, color: Some("#2F2530"), group: None }),
        ("Xojo", Language { name: "Xojo", language_type: LanguageType::Programming, color: None, group: None }),
        ("Nginx", Language { name: "Nginx", language_type: LanguageType::Data, color: None, group: None }),
        ("MLIR", Language { name: "MLIR", language_type: LanguageType::Programming, color: Some("#5EC8DB"), group: None }),
        ("HTML", Language { name: "HTML", language_type: LanguageType::Markup, color: Some("#e34c26"), group: None }),
        ("Parrot Internal Representation", Language { name: "Parrot Internal Representation", language_type: LanguageType::Programming, color: None, group: Some("Parrot") }),
        ("GAMS", Language { name: "GAMS", language_type: LanguageType::Programming, color: None, group: None }),
        ("AutoHotkey", Language { name: "AutoHotkey", language_type: LanguageType::Programming, color: Some("#6594b9"), group: None }),
        ("Volt", Language { name: "Volt", language_type: LanguageType::Programming, color: Some("#1F1F1F"), group: None }),
        ("TI Program", Language { name: "TI Program", language_type: LanguageType::Programming, color: Some("#A0AA87"), group: None }),
        ("API Blueprint", Language { name: "API Blueprint", language_type: LanguageType::Markup, color: Some("#2ACCA8"), group: None }),
        ("Self", Language { name: "Self", language_type: LanguageType::Programming, color: Some("#0579aa"), group: None }),
        ("Nim", Language { name: "Nim", language_type: LanguageType::Programming, color: Some("#37775b"), group: None }),
        ("Ninja", Language { name: "Ninja", language_type: LanguageType::Data, color: None, group: None }),
        ("RUNOFF", Language { name: "RUNOFF", language_type: LanguageType::Markup, color: Some("#665a4e"), group: None }),
        ("Pawn", Language { name: "Pawn", language_type: LanguageType::Programming, color: Some("#dbb284"), group: None }),
        ("Roff", Language { name: "Roff", language_type: LanguageType::Markup, color: Some("#ecdebe"), group: None }),
        ("CodeQL", Language { name: "CodeQL", language_type: LanguageType::Programming, color: None, group: None }),
        ("BitBake", Language { name: "BitBake", language_type: LanguageType::Programming, color: None, group: None }),
        ("Prolog", Language { name: "Prolog", language_type: LanguageType::Programming, color: Some("#74283c"), group: None }),
        ("VHDL", Language { name: "VHDL", language_type: LanguageType::Programming, color: Some("#adb2cb"), group: None }),
        ("Arc", Language { name: "Arc", language_type: LanguageType::Programming, color: Some("#aa2afe"), group: None }),
        ("Rich Text Format", Language { name: "Rich Text Format", language_type: LanguageType::Markup, color: None, group: None }),
        ("Wavefront Object", Language { name: "Wavefront Object", language_type: LanguageType::Data, color: None, group: None }),
        ("1C Enterprise", Language { name: "1C Enterprise", language_type: LanguageType::Programming, color: Some("#814CCC"), group: None }),
        ("J", Language { name: "J", language_type: LanguageType::Programming, color: Some("#9EEDFF"), group: None }),
        ("GraphQL", Language { name: "GraphQL", language_type: LanguageType::Data, color: None, group: None }),
        ("PicoLisp", Language { name: "PicoLisp", language_type: LanguageType::Programming, color: None, group: None }),
        ("Web Ontology Language", Language { name: "Web Ontology Language", language_type: LanguageType::Data, color: None, group: None }),
        ("COBOL", Language { name: "COBOL", language_type: LanguageType::Programming, color: None, group: None }),
        ("EmberScript", Language { name: "EmberScript", language_type: LanguageType::Programming, color: Some("#FFF4F3"), group: None }),
        ("Sass", Language { name: "Sass", language_type: LanguageType::Markup, color: None, group: Some("CSS") }),
        ("SCSS", Language { name: "SCSS", language_type: LanguageType::Markup, color: None, group: Some("CSS") }),
        ("NSIS", Language { name: "NSIS", language_type: LanguageType::Programming, color: None, group: None }),
        ("Java Server Pages", Language { name: "Java Server Pages", language_type: LanguageType::Programming, color: None, group: Some("Java") }),
        ("G-code", Language { name: "G-code", language_type: LanguageType::Programming, color: Some("#D08CF2"), group: None }),
        ("Alloy", Language { name: "Alloy", language_type: LanguageType::Programming, color: Some("#64C800"), group: None }),
        ("Graphviz (DOT)", Language { name: "Graphviz (DOT)", language_type: LanguageType::Data, color: None, group: None }),
        ("Latte", Language { name: "Latte", language_type: LanguageType::Markup, color: None, group: Some("HTML") }),
        ("Common Lisp", Language { name: "Common Lisp", language_type: LanguageType::Programming, color: Some("#3fb68b"), group: None }),
        ("ABAP", Language { name: "ABAP", language_type: LanguageType::Programming, color: Some("#E8274B"), group: None }),
        ("EQ", Language { name: "EQ", language_type: LanguageType::Programming, color: Some("#a78649"), group: None }),
        ("WebVTT", Language { name: "WebVTT", language_type: LanguageType::Data, color: None, group: None }),
        ("GCC Machine Description", Language { name: "GCC Machine Description", language_type: LanguageType::Programming, color: None, group: None }),
        ("POV-Ray SDL", Language { name: "POV-Ray SDL", language_type: LanguageType::Programming, color: None, group: None }),
        ("OpenType Feature File", Language { name: "OpenType Feature File", language_type: LanguageType::Data, color: None, group: None }),
        ("Metal", Language { name: "Metal", language_type: LanguageType::Programming, color: Some("#8f14e9"), group: None }),
        ("Monkey", Language { name: "Monkey", language_type: LanguageType::Programming, color: None, group: None }),
        ("SMT", Language { name: "SMT", language_type: LanguageType::Programming, color: None, group: None }),
        ("NetLinx", Language { name: "NetLinx", language_type: LanguageType::Programming, color: Some("#0aa0ff"), group: None }),
        ("RPC", Language { name: "RPC", language_type: LanguageType::Programming, color: None, group: None }),
        ("Makefile", Language { name: "Makefile", language_type: LanguageType::Programming, color: Some("#427819"), group: None }),
        ("wisp", Language { name: "wisp", language_type: LanguageType::Programming, color: Some("#7582D1"), group: None }),
        ("KiCad Schematic", Language { name: "KiCad Schematic", language_type: LanguageType::Data, color: None, group: None }),
        ("Slim", Language { name: "Slim", language_type: LanguageType::Markup, color: None, group: Some("HTML") }),
        ("IDL", Language { name: "IDL", language_type: LanguageType::Programming, color: Some("#a3522f"), group: None }),
        ("INI", Language { name: "INI", language_type: LanguageType::Data, color: None, group: None }),
        ("LoomScript", Language { name: "LoomScript", language_type: LanguageType::Programming, color: None, group: None }),
        ("ZenScript", Language { name: "ZenScript", language_type: LanguageType::Programming, color: Some("#00BCD1"), group: None }),
        ("Omgrofl", Language { name: "Omgrofl", language_type: LanguageType::Programming, color: Some("#cabbff"), group: None }),
        ("OpenStep Property List", Language { name: "OpenStep Property List", language_type: LanguageType::Data, color: None, group: None }),
        ("Scheme", Language { name: "Scheme", language_type: LanguageType::Programming, color: Some("#1e4aec"), group: None }),
        ("R", Language { name: "R", language_type: LanguageType::Programming, color: Some("#198CE7"), group: None }),
        ("Lasso", Language { name: "Lasso", language_type: LanguageType::Programming, color: Some("#999999"), group: None }),
        ("SaltStack", Language { name: "SaltStack", language_type: LanguageType::Programming, color: Some("#646464"), group: None }),
        ("Python", Language { name: "Python", language_type: LanguageType::Programming, color: Some("#3572A5"), group: None }),
        ("Io", Language { name: "Io", language_type: LanguageType::Programming, color: Some("#a9188d"), group: None }),
        ("Ox", Language { name: "Ox", language_type: LanguageType::Programming, color: None, group: None }),
        ("Smali", Language { name: "Smali", language_type: LanguageType::Programming, color: None, group: None }),
        ("HLSL", Language { name: "HLSL", language_type: LanguageType::Programming, color: None, group: None }),
        ("Literate Agda", Language { name: "Literate Agda", language_type: LanguageType::Programming, color: None, group: Some("Agda") }),
        ("Zeek", Language { name: "Zeek", language_type: LanguageType::Programming, color: None, group: None }),
        ("CSV", Language { name: "CSV", language_type: LanguageType::Data, color: None, group: None }),
        ("Adobe Font Metrics", Language { name: "Adobe Font Metrics", language_type: LanguageType::Data, color: None, group: None }),
        ("DataWeave", Language { name: "DataWeave", language_type: LanguageType::Programming, color: Some("#003a52"), group: None }),
        ("Julia", Language { name: "Julia", language_type: LanguageType::Programming, color: Some("#a270ba"), group: None }),
        ("Type Language", Language { name: "Type Language", language_type: LanguageType::Data, color: None, group: None }),
        ("Thrift", Language { name: "Thrift", language_type: LanguageType::Programming, color: None, group: None }),
        ("Gherkin", Language { name: "Gherkin", language_type: LanguageType::Programming, color: Some("#5B2063"), group: None }),
        ("Linux Kernel Module", Language { name: "Linux Kernel Module", language_type: LanguageType::Data, color: None, group: None }),
        ("Squirrel", Language { name: "Squirrel", language_type: LanguageType::Programming, color: Some("#800000"), group: None }),
        ("Redcode", Language { name: "Redcode", language_type: LanguageType::Programming, color: None, group: None }),
        ("HyPhy", Language { name: "HyPhy", language_type: LanguageType::Programming, color: None, group: None }),
        ("Xtend", Language { name: "Xtend", language_type: LanguageType::Programming, color: None, group: None }),
        ("JSON", Language { name: "JSON", language_type: LanguageType::Data, color: None, group: None }),
        ("Eiffel", Language { name: "Eiffel", language_type: LanguageType::Programming, color: Some("#946d57"), group: None }),
        ("Batchfile+CaretObfuscated", Language { name: "Batchfile+CaretObfuscated", language_type: LanguageType::Programming, color: Some("#C1F12E"), group: Some("Batchfile") }),
        ("PureBasic", Language { name: "PureBasic", language_type: LanguageType::Programming, color: Some("#5a6986"), group: None }),
        ("Literate CoffeeScript", Language { name: "Literate CoffeeScript", language_type: LanguageType::Programming, color: None, group: Some("CoffeeScript") }),
        ("JavaScript+ObfuscatorIO", Language { name: "JavaScript+ObfuscatorIO", language_type: LanguageType::Programming, color: Some("#f1e05a"), group: Some("JavaScript") }),
        ("Papyrus", Language { name: "Papyrus", language_type: LanguageType::Programming, color: Some("#6600cc"), group: None }),
        ("Elixir", Language { name: "Elixir", language_type: LanguageType::Programming, color: Some("#6e4a7e"), group: None }),
        ("Genie", Language { name: "Genie", language_type: LanguageType::Programming, color: Some("#fb855d"), group: None }),
        ("CoNLL-U", Language { name: "CoNLL-U", language_type: LanguageType::Data, color: None, group: None }),
        ("LTspice Symbol", Language { name: "LTspice Symbol", language_type: LanguageType::Data, color: None, group: None }),
        ("Stata", Language { name: "Stata", language_type: LanguageType::Programming, color: None, group: None }),
        ("Eagle", Language { name: "Eagle", language_type: LanguageType::Data, color: None, group: None }),
        ("Agda", Language { name: "Agda", language_type: LanguageType::Programming, color: Some("#315665"), group: None }),
        ("Odin", Language { name: "Odin", language_type: LanguageType::Programming, color: Some("#60AFFE"), group: None }),
        ("JSONLD", Language { name: "JSONLD", language_type: LanguageType::Data, color: None, group: None }),
        ("PLpgSQL", Language { name: "PLpgSQL", language_type: LanguageType::Programming, color: None, group: None }),
        ("Unix Assembly", Language { name: "Unix Assembly", language_type: LanguageType::Programming, color: None, group: Some("Assembly") }),
        ("Texinfo", Language { name: "Texinfo", language_type: LanguageType::Prose, color: None, group: None }),
        ("Erlang", Language { name: "Erlang", language_type: LanguageType::Programming, color: Some("#B83998"), group: None }),
        ("KRL", Language { name: "KRL", language_type: LanguageType::Programming, color: Some("#28430A"), group: None }),
        ("desktop", Language { name: "desktop", language_type: LanguageType::Data, color: None, group: None }),
        ("Grace", Language { name: "Grace", language_type: LanguageType::Programming, color: None, group: None }),
        ("Component Pascal", Language { name: "Component Pascal", language_type: LanguageType::Programming, color: Some("#B0CE4E"), group: None }),
        ("P4", Language { name: "P4", language_type: LanguageType::Programming, color: Some("#7055b5"), group: None }),
        ("AMPL", Language { name: "AMPL", language_type: LanguageType::Programming, color: Some("#E6EFBB"), group: None }),
        ("Slash", Language { name: "Slash", language_type: LanguageType::Programming, color: Some("#007eff"), group: None }),
        ("Hack", Language { name: "Hack", language_type: LanguageType::Programming, color: Some("#878787"), group: None }),
        ("Solidity", Language { name: "Solidity", language_type: LanguageType::Programming, color: Some("#AA6746"), group: None }),
        ("Swift", Language { name: "Swift", language_type: LanguageType::Programming, color: Some("#ffac45"), group: None }),
        ("Pure Data", Language { name: "Pure Data", language_type: LanguageType::Data, color: None, group: None }),
        ("UrWeb", Language { name: "UrWeb", language_type: LanguageType::Programming, color: None, group: None }),
        ("Jsonnet", Language { name: "Jsonnet", language_type: LanguageType::Programming, color: Some("#0064bd"), group: None }),
        ("Frege", Language { name: "Frege", language_type: LanguageType::Programming, color: Some("#00cafe"), group: None }),
        ("KiCad Layout", Language { name: "KiCad Layout", language_type: LanguageType::Data, color: None, group: None }),
        ("SQL", Language { name: "SQL", language_type: LanguageType::Data, color: None, group: None }),
        ("Isabelle", Language { name: "Isabelle", language_type: LanguageType::Programming, color: Some("#FEFE00"), group: None }),
        ("Red", Language { name: "Red", language_type: LanguageType::Programming, color: Some("#f50000"), group: None }),
        ("PogoScript", Language { name: "PogoScript", language_type: LanguageType::Programming, color: Some("#d80074"), group: None }),
        ("Verilog", Language { name: "Verilog", language_type: LanguageType::Programming, color: Some("#b2b7f8"), group: None }),
        ("JFlex", Language { name: "JFlex", language_type: LanguageType::Programming, color: None, group: Some("Lex") }),
        ("Jison Lex", Language { name: "Jison Lex", language_type: LanguageType::Programming, color: None, group: Some("Lex") }),
        ("CoffeeScript", Language { name: "CoffeeScript", language_type: LanguageType::Programming, color: Some("#244776"), group: None }),
        ("F#", Language { name: "F#", language_type: LanguageType::Programming, color: Some("#b845fc"), group: None }),
        ("Fortran", Language { name: "Fortran", language_type: LanguageType::Programming, color: Some("#4d41b1"), group: None }),
        ("Tea", Language { name: "Tea", language_type: LanguageType::Markup, color: None, group: None }),
        ("Sage", Language { name: "Sage", language_type: LanguageType::Programming, color: None, group: Some("Python") }),
        ("Factor", Language { name: "Factor", language_type: LanguageType::Programming, color: Some("#636746"), group: None }),
        ("Emacs Lisp", Language { name: "Emacs Lisp", language_type: LanguageType::Programming, color: Some("#c065db"), group: None }),
        ("Parrot", Language { name: "Parrot", language_type: LanguageType::Programming, color: Some("#f3ca0a"), group: None }),
        ("AspectJ", Language { name: "AspectJ", language_type: LanguageType::Programming, color: Some("#a957b0"), group: None }),
        ("Regular Expression", Language { name: "Regular Expression", language_type: LanguageType::Data, color: None, group: None }),
        ("PostScript", Language { name: "PostScript", language_type: LanguageType::Markup, color: Some("#da291c"), group: None }),
        ("Edje Data Collection", Language { name: "Edje Data Collection", language_type: LanguageType::Data, color: None, group: None }),
        ("DIGITAL Command Language", Language { name: "DIGITAL Command Language", language_type: LanguageType::Programming, color: None, group: None }),
        ("HCL", Language { name: "HCL", language_type: LanguageType::Programming, color: None, group: None }),
        ("Readline Config", Language { name: "Readline Config", language_type: LanguageType::Data, color: None, group: Some("INI") }),
        ("Org", Language { name: "Org", language_type: LanguageType::Prose, color: None, group: None }),
        ("ShaderLab", Language { name: "ShaderLab", language_type: LanguageType::Programming, color: None, group: None }),
        ("RPM Spec", Language { name: "RPM Spec", language_type: LanguageType::Data, color: None, group: None }),
        ("Ada", Language { name: "Ada", language_type: LanguageType::Programming, color: Some("#02f88c"), group: None }),
        ("Module Management System", Language { name: "Module Management System", language_type: LanguageType::Programming, color: None, group: None }),
        ("VBA", Language { name: "VBA", language_type: LanguageType::Programming, color: Some("#867db1"), group: None }),
        ("DNS Zone", Language { name: "DNS Zone", language_type: LanguageType::Data, color: None, group: None }),
        ("Jison", Language { name: "Jison", language_type: LanguageType::Programming, color: None, group: Some("Yacc") }),
        ("Twig", Language { name: "Twig", language_type: LanguageType::Markup, color: None, group: Some("HTML") }),
        ("Go", Language { name: "Go", language_type: LanguageType::Programming, color: Some("#00ADD8"), group: None }),
        ("Bluespec", Language { name: "Bluespec", language_type: LanguageType::Programming, color: None, group: None }),
        ("Unity3D Asset", Language { name: "Unity3D Asset", language_type: LanguageType::Data, color: None, group: None }),
        ("YANG", Language { name: "YANG", language_type: LanguageType::Data, color: None, group: None }),
        ("WebIDL", Language { name: "WebIDL", language_type: LanguageType::Programming, color: None, group: None }),
        ("JavaScript+ERB", Language { name: "JavaScript+ERB", language_type: LanguageType::Programming, color: None, group: Some("JavaScript") }),
        ("Ragel", Language { name: "Ragel", language_type: LanguageType::Programming, color: Some("#9d5200"), group: None }),
        ("Scala", Language { name: "Scala", language_type: LanguageType::Programming, color: Some("#c22d40"), group: None }),
        ("Mirah", Language { name: "Mirah", language_type: LanguageType::Programming, color: Some("#c7a938"), group: None }),
        ("Dhall", Language { name: "Dhall", language_type: LanguageType::Programming, color: Some("#dfafff"), group: None }),
        ("CLIPS", Language { name: "CLIPS", language_type: LanguageType::Programming, color: None, group: None }),
        ("FIGlet Font", Language { name: "FIGlet Font", language_type: LanguageType::Data, color: None, group: None }),
        ("YARA", Language { name: "YARA", language_type: LanguageType::Programming, color: Some("#220000"), group: None }),
        ("CMake", Language { name: "CMake", language_type: LanguageType::Programming, color: None, group: None }),
        ("Maven POM", Language { name: "Maven POM", language_type: LanguageType::Data, color: None, group: None }),
        ("TSQL", Language { name: "TSQL", language_type: LanguageType::Programming, color: None, group: None }),
        ("Mercury", Language { name: "Mercury", language_type: LanguageType::Programming, color: Some("#ff2b2b"), group: None }),
        ("HTTP", Language { name: "HTTP", language_type: LanguageType::Data, color: None, group: None }),
        ("Glyph", Language { name: "Glyph", language_type: LanguageType::Programming, color: Some("#c1ac7f"), group: None }),
        ("Opal", Language { name: "Opal", language_type: LanguageType::Programming, color: Some("#f7ede0"), group: None }),
        ("Cuda", Language { name: "Cuda", language_type: LanguageType::Programming, color: Some("#3A4E3A"), group: None }),
        ("JSON5", Language { name: "JSON5", language_type: LanguageType::Data, color: None, group: None }),
        ("Dockerfile", Language { name: "Dockerfile", language_type: LanguageType::Programming, color: Some("#384d54"), group: None }),
        ("Pony", Language { name: "Pony", language_type: LanguageType::Programming, color: None, group: None }),
        ("LOLCODE", Language { name: "LOLCODE", language_type: LanguageType::Programming, color: Some("#cc9900"), group: None }),
        ("LookML", Language { name: "LookML", language_type: LanguageType::Programming, color: Some("#652B81"), group: None }),
        ("Assembly", Language { name: "Assembly", language_type: LanguageType::Programming, color: Some("#6E4C13"), group: None }),
        ("JavaScript+Packer", Language { name: "JavaScript+Packer", language_type: LanguageType::Programming, color: Some("#f1e05a"), group: Some("JavaScript") }),
        ("REALbasic", Language { name: "REALbasic", language_type: LanguageType::Programming, color: None, group: None }),
        ("Batchfile", Language { name: "Batchfile", language_type: LanguageType::Programming, color: Some("#C1F12E"), group: None }),
        ("Pascal", Language { name: "Pascal", language_type: LanguageType::Programming, color: Some("#E3F171"), group: None }),
        ("Wollok", Language { name: "Wollok", language_type: LanguageType::Programming, color: Some("#a23738"), group: None }),
        ("YASnippet", Language { name: "YASnippet", language_type: LanguageType::Markup, color: Some("#32AB90"), group: None }),
        ("Nu", Language { name: "Nu", language_type: LanguageType::Programming, color: Some("#c9df40"), group: None }),
        ("Max", Language { name: "Max", language_type: LanguageType::Programming, color: Some("#c4a79c"), group: None }),
        ("ECL", Language { name: "ECL", language_type: LanguageType::Programming, color: Some("#8a1267"), group: None }),
        ("Haskell", Language { name: "Haskell", language_type: LanguageType::Programming, color: Some("#5e5086"), group: None }),
        ("ECLiPSe", Language { name: "ECLiPSe", language_type: LanguageType::Programming, color: None, group: Some("prolog") }),
        ("D-ObjDump", Language { name: "D-ObjDump", language_type: LanguageType::Data, color: None, group: None }),
        ("HTML+ERB", Language { name: "HTML+ERB", language_type: LanguageType::Markup, color: None, group: Some("HTML") }),
        ("Kit", Language { name: "Kit", language_type: LanguageType::Markup, color: None, group: None }),
        ("mcfunction", Language { name: "mcfunction", language_type: LanguageType::Programming, color: Some("#E22837"), group: None }),
        ("XS", Language { name: "XS", language_type: LanguageType::Programming, color: None, group: None }),
        ("Dart", Language { name: "Dart", language_type: LanguageType::Programming, color: Some("#00B4AB"), group: None }),
        ("JSONiq", Language { name: "JSONiq", language_type: LanguageType::Programming, color: Some("#40d47e"), group: None }),
        ("MoonScript", Language { name: "MoonScript", language_type: LanguageType::Programming, color: None, group: None }),
        ("ATS", Language { name: "ATS", language_type: LanguageType::Programming, color: Some("#1ac620"), group: None }),
        ("OCaml", Language { name: "OCaml", language_type: LanguageType::Programming, color: Some("#3be133"), group: None }),
        ("SQLPL", Language { name: "SQLPL", language_type: LanguageType::Programming, color: None, group: None }),
        ("Jolie", Language { name: "Jolie", language_type: LanguageType::Programming, color: Some("#843179"), group: None }),
        ("Apollo Guidance Computer", Language { name: "Apollo Guidance Computer", language_type: LanguageType::Programming, color: None, group: Some("Assembly") }),
        ("PLSQL", Language { name: "PLSQL", language_type: LanguageType::Programming, color: Some("#dad8d8"), group: None }),
        ("MUF", Language { name: "MUF", language_type: LanguageType::Programming, color: None, group: Some("Forth") }),
        ("Vue", Language { name: "Vue", language_type: LanguageType::Markup, color: Some("#2c3e50"), group: None }),
        ("GN", Language { name: "GN", language_type: LanguageType::Data, color: None, group: None }),
        ("SubRip Text", Language { name: "SubRip Text", language_type: LanguageType::Data, color: None, group: None }),
        ("Alpine Abuild", Language { name: "Alpine Abuild", language_type: LanguageType::Programming, color: None, group: Some("Shell") }),
        ("Git Attributes", Language { name: "Git Attributes", language_type: LanguageType::Data, color: None, group: Some("INI") }),
        ("TLA", Language { name: "TLA", language_type: LanguageType::Programming, color: None, group: None }),
        ("Chapel", Language { name: "Chapel", language_type: LanguageType::Programming, color: Some("#8dc63f"), group: None }),
        ("TOML", Language { name: "TOML", language_type: LanguageType::Data, color: None, group: None }),
        ("Smarty", Language { name: "Smarty", language_type: LanguageType::Programming, color: None, group: None }),
        ("MTML", Language { name: "MTML", language_type: LanguageType::Markup, color: Some("#b7e1f4"), group: None }),
        ("Filterscript", Language { name: "Filterscript", language_type: LanguageType::Programming, color: None, group: Some("RenderScript") }),
        ("NL", Language { name: "NL", language_type: LanguageType::Data, color: None, group: None }),
        ("Gettext Catalog", Language { name: "Gettext Catalog", language_type: LanguageType::Prose, color: None, group: None }),
        ("Meson", Language { name: "Meson", language_type: LanguageType::Programming, color: Some("#007800"), group: None }),
        ("Kotlin", Language { name: "Kotlin", language_type: LanguageType::Programming, color: Some("#F18E33"), group: None }),
        ("Objective-J", Language { name: "Objective-J", language_type: LanguageType::Programming, color: Some("#ff0c5a"), group: None }),
        ("SystemVerilog", Language { name: "SystemVerilog", language_type: LanguageType::Programming, color: Some("#DAE1C2"), group: None }),
        ("SQF", Language { name: "SQF", language_type: LanguageType::Programming, color: Some("#3F3F3F"), group: None }),
        ("TypeScript", Language { name: "TypeScript", language_type: LanguageType::Programming, color: Some("#2b7489"), group: None }),
        ("Common Workflow Language", Language { name: "Common Workflow Language", language_type: LanguageType::Programming, color: Some("#B5314C"), group: None }),
        ("mupad", Language { name: "mupad", language_type: LanguageType::Programming, color: None, group: None }),
        ("Rascal", Language { name: "Rascal", language_type: LanguageType::Programming, color: Some("#fffaa0"), group: None }),
        ("Groovy", Language { name: "Groovy", language_type: LanguageType::Programming, color: Some("#e69f56"), group: None }),
        ("Mathematica", Language { name: "Mathematica", language_type: LanguageType::Programming, color: None, group: None }),
        ("Wavefront Material", Language { name: "Wavefront Material", language_type: LanguageType::Data, color: None, group: None }),
        ("Golo", Language { name: "Golo", language_type: LanguageType::Programming, color: Some("#88562A"), group: None }),
        ("TeX", Language { name: "TeX", language_type: LanguageType::Markup, color: Some("#3D6117"), group: None }),
        ("AngelScript", Language { name: "AngelScript", language_type: LanguageType::Programming, color: Some("#C7D7DC"), group: None }),
        ("Python traceback", Language { name: "Python traceback", language_type: LanguageType::Data, color: None, group: Some("Python") }),
        ("KiCad Legacy Layout", Language { name: "KiCad Legacy Layout", language_type: LanguageType::Data, color: None, group: None }),
        ("TSX", Language { name: "TSX", language_type: LanguageType::Programming, color: None, group: Some("TypeScript") }),
        ("Zig", Language { name: "Zig", language_type: LanguageType::Programming, color: Some("#ec915c"), group: None }),
        ("PHP", Language { name: "PHP", language_type: LanguageType::Programming, color: Some("#4F5D95"), group: None }),
        ("Modula-2", Language { name: "Modula-2", language_type: LanguageType::Programming, color: None, group: None }),
        ("XC", Language { name: "XC", language_type: LanguageType::Programming, color: Some("#99DA07"), group: None }),
        ("C-ObjDump", Language { name: "C-ObjDump", language_type: LanguageType::Data, color: None, group: None }),
        ("Easybuild", Language { name: "Easybuild", language_type: LanguageType::Data, color: None, group: Some("Python") }),
        ("Opa", Language { name: "Opa", language_type: LanguageType::Programming, color: None, group: None }),
        ("Gentoo Eclass", Language { name: "Gentoo Eclass", language_type: LanguageType::Programming, color: None, group: Some("Shell") }),
        ("Dogescript", Language { name: "Dogescript", language_type: LanguageType::Programming, color: Some("#cca760"), group: None }),
        ("BlitzMax", Language { name: "BlitzMax", language_type: LanguageType::Programming, color: Some("#cd6400"), group: None }),
        ("World of Warcraft Addon Data", Language { name: "World of Warcraft Addon Data", language_type: LanguageType::Data, color: None, group: None }),
        ("Gerber Image", Language { name: "Gerber Image", language_type: LanguageType::Data, color: None, group: None }),
        ("NewLisp", Language { name: "NewLisp", language_type: LanguageType::Programming, color: Some("#87AED7"), group: None }),
        ("NCL", Language { name: "NCL", language_type: LanguageType::Programming, color: Some("#28431f"), group: None }),
        ("QML", Language { name: "QML", language_type: LanguageType::Programming, color: Some("#44a51c"), group: None }),
        ("Protocol Buffer", Language { name: "Protocol Buffer", language_type: LanguageType::Data, color: None, group: None }),
        ("HTML+Django", Language { name: "HTML+Django", language_type: LanguageType::Markup, color: None, group: Some("HTML") }),
        ("Text", Language { name: "Text", language_type: LanguageType::Prose, color: None, group: None }),
        ("ANTLR", Language { name: "ANTLR", language_type: LanguageType::Programming, color: Some("#9DC3FF"), group: None }),
        ("ObjectScript", Language { name: "ObjectScript", language_type: LanguageType::Programming, color: Some("#424893"), group: None }),
        ("Graph Modeling Language", Language { name: "Graph Modeling Language", language_type: LanguageType::Data, color: None, group: None }),
        ("PigLatin", Language { name: "PigLatin", language_type: LanguageType::Programming, color: Some("#fcd7de"), group: None }),
        ("Standard ML", Language { name: "Standard ML", language_type: LanguageType::Programming, color: Some("#dc566d"), group: None }),
        ("ooc", Language { name: "ooc", language_type: LanguageType::Programming, color: Some("#b0b77e"), group: None }),
        ("Rust", Language { name: "Rust", language_type: LanguageType::Programming, color: Some("#dea584"), group: None }),
        ("SPARQL", Language { name: "SPARQL", language_type: LanguageType::Data, color: None, group: None }),
        ("Textile", Language { name: "Textile", language_type: LanguageType::Prose, color: None, group: None }),
        ("Uno", Language { name: "Uno", language_type: LanguageType::Programming, color: None, group: None }),
        ("JavaScript+JSFuck", Language { name: "JavaScript+JSFuck", language_type: LanguageType::Programming, color: Some("#f1e05a"), group: Some("JavaScript") }),
        ("Cool", Language { name: "Cool", language_type: LanguageType::Programming, color: None, group: None }),
        ("Yacc", Language { name: "Yacc", language_type: LanguageType::Programming, color: Some("#4B6C4B"), group: None }),
        ("Apex", Language { name: "Apex", language_type: LanguageType::Programming, color: None, group: None }),
        ("EditorConfig", Language { name: "EditorConfig", language_type: LanguageType::Data, color: None, group: Some("INI") }),
        ("Logos", Language { name: "Logos", language_type: LanguageType::Programming, color: None, group: None }),
        ("NetLogo", Language { name: "NetLogo", language_type: LanguageType::Programming, color: Some("#ff6375"), group: None }),
        ("Moocode", Language { name: "Moocode", language_type: LanguageType::Programming, color: None, group: None }),
        ("VBA+JSONPacked", Language { name: "VBA+JSONPacked", language_type: LanguageType::Programming, color: Some("#867db1"), group: Some("VBA") }),
        ("Slice", Language { name: "Slice", language_type: LanguageType::Programming, color: Some("#003fa2"), group: None }),
        ("SVG", Language { name: "SVG", language_type: LanguageType::Data, color: None, group: None }),
        ("STON", Language { name: "STON", language_type: LanguageType::Data, color: None, group: Some("Smalltalk") }),
        ("Wget Config", Language { name: "Wget Config", language_type: LanguageType::Data, color: None, group: Some("INI") }),
        ("Game Maker Language", Language { name: "Game Maker Language", language_type: LanguageType::Programming, color: Some("#71b417"), group: None }),
        ("C++", Language { name: "C++", language_type: LanguageType::Programming, color: Some("#f34b7d"), group: None }),
        ("reStructuredText", Language { name: "reStructuredText", language_type: LanguageType::Prose, color: None, group: None }),
        ("Unified Parallel C", Language { name: "Unified Parallel C", language_type: LanguageType::Programming, color: None, group: Some("C") }),
        ("WebAssembly", Language { name: "WebAssembly", language_type: LanguageType::Programming, color: Some("#04133b"), group: None }),
        ("Zephir", Language { name: "Zephir", language_type: LanguageType::Programming, color: Some("#118f9e"), group: None }),
        ("RHTML", Language { name: "RHTML", language_type: LanguageType::Markup, color: None, group: Some("HTML") }),
        ("V", Language { name: "V", language_type: LanguageType::Programming, color: Some("#5d87bd"), group: None }),
        ("Ballerina", Language { name: "Ballerina", language_type: LanguageType::Programming, color: Some("#FF5000"), group: None }),
        ("Gradle", Language { name: "Gradle", language_type: LanguageType::Data, color: None, group: None }),
        ("Motorola 68K Assembly", Language { name: "Motorola 68K Assembly", language_type: LanguageType::Programming, color: None, group: Some("Assembly") }),
        ("MiniD", Language { name: "MiniD", language_type: LanguageType::Programming, color: None, group: None }),
        ("EBNF", Language { name: "EBNF", language_type: LanguageType::Data, color: None, group: None }),
        ("Nit", Language { name: "Nit", language_type: LanguageType::Programming, color: Some("#009917"), group: None }),
        ("JavaScript+URIEncoded", Language { name: "JavaScript+URIEncoded", language_type: LanguageType::Programming, color: Some("#f1e05a"), group: Some("JavaScript") }),
        ("Glyph Bitmap Distribution Format", Language { name: "Glyph Bitmap Distribution Format", language_type: LanguageType::Data, color: None, group: None }),
        ("Closure Templates", Language { name: "Closure Templates", language_type: LanguageType::Markup, color: None, group: Some("HTML") }),
        ("Mako", Language { name: "Mako", language_type: LanguageType::Programming, color: None, group: None }),
        ("Microsoft Developer Studio Project", Language { name: "Microsoft Developer Studio Project", language_type: LanguageType::Data, color: None, group: None }),
        ("Gnuplot", Language { name: "Gnuplot", language_type: LanguageType::Programming, color: Some("#f0a9f0"), group: None }),
        ("HiveQL", Language { name: "HiveQL", language_type: LanguageType::Programming, color: Some("#dce200"), group: None }),
        ("MATLAB", Language { name: "MATLAB", language_type: LanguageType::Programming, color: Some("#e16737"), group: None }),
        ("JSON with Comments", Language { name: "JSON with Comments", language_type: LanguageType::Data, color: None, group: Some("JSON") }),
        ("ASP", Language { name: "ASP", language_type: LanguageType::Programming, color: Some("#6a40fd"), group: None }),
        ("XProc", Language { name: "XProc", language_type: LanguageType::Programming, color: None, group: None }),
        ("ApacheConf", Language { name: "ApacheConf", language_type: LanguageType::Data, color: None, group: None }),
        ("Nix", Language { name: "Nix", language_type: LanguageType::Programming, color: Some("#7e7eff"), group: None }),
        ("OpenRC runscript", Language { name: "OpenRC runscript", language_type: LanguageType::Programming, color: None, group: Some("Shell") }),
        ("Starlark", Language { name: "Starlark", language_type: LanguageType::Programming, color: Some("#76d275"), group: None }),
        ("LabVIEW", Language { name: "LabVIEW", language_type: LanguageType::Programming, color: None, group: None }),
        ("Brightscript", Language { name: "Brightscript", language_type: LanguageType::Programming, color: None, group: None }),
        ("Ant Build System", Language { name: "Ant Build System", language_type: LanguageType::Data, color: None, group: None }),
        ("VBScript+HTMLDecoy", Language { name: "VBScript+HTMLDecoy", language_type: LanguageType::Programming, color: Some("#15dcdc"), group: Some("VBScript") }),
        ("Processing", Language { name: "Processing", language_type: LanguageType::Programming, color: Some("#0096D8"), group: None }),
        ("Coq", Language { name: "Coq", language_type: LanguageType::Programming, color: None, group: None }),
        ("UnrealScript", Language { name: "UnrealScript", language_type: LanguageType::Programming, color: Some("#a54c4d"), group: None }),
        ("JavaScript+HexString", Language { name: "JavaScript+HexString", language_type: LanguageType::Programming, color: Some("#f1e05a"), group: Some("JavaScript") }),
        ("cURL Config", Language { name: "cURL Config", language_type: LanguageType::Data, color: None, group: Some("INI") }),
        ("Scaml", Language { name: "Scaml", language_type: LanguageType::Markup, color: None, group: Some("HTML") }),
        ("q", Language { name: "q", language_type: LanguageType::Programming, color: Some("#0040cd"), group: None }),
        ("Raw token data", Language { name: "Raw token data", language_type: LanguageType::Data, color: None, group: None }),
        ("Turtle", Language { name: "Turtle", language_type: LanguageType::Data, color: None, group: None }),
        ("Pic", Language { name: "Pic", language_type: LanguageType::Markup, color: None, group: Some("Roff") }),
        ("Reason", Language { name: "Reason", language_type: LanguageType::Programming, color: Some("#ff5847"), group: None }),
        ("Ren'Py", Language { name: "Ren'Py", language_type: LanguageType::Programming, color: Some("#ff7f7f"), group: None }),
        ("Forth", Language { name: "Forth", language_type: LanguageType::Programming, color: Some("#341708"), group: None }),
        ("Csound Document", Language { name: "Csound Document", language_type: LanguageType::Programming, color: None, group: None }),
        ("Creole", Language { name: "Creole", language_type: LanguageType::Prose, color: None, group: None }),
        ("Prisma", Language { name: "Prisma", language_type: LanguageType::Data, color: None, group: None }),
        ("NetLinx+ERB", Language { name: "NetLinx+ERB", language_type: LanguageType::Programming, color: Some("#747faa"), group: None }),
        ("Crystal", Language { name: "Crystal", language_type: LanguageType::Programming, color: Some("#000100"), group: None }),
        ("Modula-3", Language { name: "Modula-3", language_type: LanguageType::Programming, color: Some("#223388"), group: None }),
        ("Cython", Language { name: "Cython", language_type: LanguageType::Programming, color: None, group: Some("Python") }),
        ("Haxe", Language { name: "Haxe", language_type: LanguageType::Programming, color: Some("#df7900"), group: None }),
        ("RenderScript", Language { name: "RenderScript", language_type: LanguageType::Programming, color: None, group: None }),
        ("Scilab", Language { name: "Scilab", language_type: LanguageType::Programming, color: None, group: None }),
        ("Isabelle ROOT", Language { name: "Isabelle ROOT", language_type: LanguageType::Programming, color: None, group: Some("Isabelle") }),
        ("NumPy", Language { name: "NumPy", language_type: LanguageType::Programming, color: None, group: Some("Python") }),
        ("Inno Setup", Language { name: "Inno Setup", language_type: LanguageType::Programming, color: None, group: None }),
        ("nanorc", Language { name: "nanorc", language_type: LanguageType::Data, color: None, group: Some("INI") }),
        ("HXML", Language { name: "HXML", language_type: LanguageType::Data, color: None, group: None }),
        ("Harbour", Language { name: "Harbour", language_type: LanguageType::Programming, color: Some("#0e60e3"), group: None }),
        ("Oxygene", Language { name: "Oxygene", language_type: LanguageType::Programming, color: Some("#cdd0e3"), group: None }),
        ("GLSL", Language { name: "GLSL", language_type: LanguageType::Programming, color: None, group: None }),
        ("Java Properties", Language { name: "Java Properties", language_type: LanguageType::Data, color: None, group: None }),
        ("Cycript", Language { name: "Cycript", language_type: LanguageType::Programming, color: None, group: None }),
        ("TXL", Language { name: "TXL", language_type: LanguageType::Programming, color: None, group: None }),
        ("Inform 7", Language { name: "Inform 7", language_type: LanguageType::Programming, color: None, group: None }),
        ("JSX", Language { name: "JSX", language_type: LanguageType::Programming, color: None, group: Some("JavaScript") }),
        ("PlantUML", Language { name: "PlantUML", language_type: LanguageType::Data, color: None, group: None }),
        ("ASN.1", Language { name: "ASN.1", language_type: LanguageType::Data, color: None, group: None }),
        ("PureScript", Language { name: "PureScript", language_type: LanguageType::Programming, color: Some("#1D222D"), group: None }),
        ("IGOR Pro", Language { name: "IGOR Pro", language_type: LanguageType::Programming, color: Some("#0000cc"), group: None }),
        ("Puppet", Language { name: "Puppet", language_type: LanguageType::Programming, color: Some("#302B6D"), group: None }),
        ("Object Data Instance Notation", Language { name: "Object Data Instance Notation", language_type: LanguageType::Data, color: None, group: None }),
        ("AppleScript", Language { name: "AppleScript", language_type: LanguageType::Programming, color: Some("#101F1F"), group: None }),
        ("AutoIt", Language { name: "AutoIt", language_type: LanguageType::Programming, color: Some("#1C3552"), group: None }),
        ("CSON", Language { name: "CSON", language_type: LanguageType::Data, color: None, group: None }),
        ("PowerShell", Language { name: "PowerShell", language_type: LanguageType::Programming, color: Some("#012456"), group: None }),
        ("Myghty", Language { name: "Myghty", language_type: LanguageType::Programming, color: None, group: None }),
        ("Idris", Language { name: "Idris", language_type: LanguageType::Programming, color: Some("#b30000"), group: None }),
        ("SSH Config", Language { name: "SSH Config", language_type: LanguageType::Data, color: None, group: Some("INI") }),
        ("Pike", Language { name: "Pike", language_type: LanguageType::Programming, color: Some("#005390"), group: None }),
        ("X BitMap", Language { name: "X BitMap", language_type: LanguageType::Data, color: None, group: Some("C") }),
        ("Bison", Language { name: "Bison", language_type: LanguageType::Programming, color: None, group: Some("Yacc") }),
        ("Racket", Language { name: "Racket", language_type: LanguageType::Programming, color: Some("#3c5caa"), group: None }),
        ("Dylan", Language { name: "Dylan", language_type: LanguageType::Programming, color: Some("#6c616e"), group: None }),
        ("Python console", Language { name: "Python console", language_type: LanguageType::Programming, color: None, group: Some("Python") }),
        ("Pod 6", Language { name: "Pod 6", language_type: LanguageType::Prose, color: None, group: None }),
        ("Clarion", Language { name: "Clarion", language_type: LanguageType::Programming, color: Some("#db901e"), group: None }),
        ("BibTeX", Language { name: "BibTeX", language_type: LanguageType::Markup, color: None, group: Some("TeX") }),
        ("LilyPond", Language { name: "LilyPond", language_type: LanguageType::Programming, color: None, group: None }),
        ("Perl", Language { name: "Perl", language_type: LanguageType::Programming, color: Some("#0298c3"), group: None }),
        ("Pug", Language { name: "Pug", language_type: LanguageType::Markup, color: None, group: Some("HTML") }),
        ("HTML+EEX", Language { name: "HTML+EEX", language_type: LanguageType::Markup, color: None, group: Some("HTML") }),
        ("Smalltalk", Language { name: "Smalltalk", language_type: LanguageType::Programming, color: Some("#596706"), group: None }),
        ("Less", Language { name: "Less", language_type: LanguageType::Markup, color: None, group: Some("CSS") }),
        ("edn", Language { name: "edn", language_type: LanguageType::Data, color: None, group: None }),
        ("YAML", Language { name: "YAML", language_type: LanguageType::Data, color: None, group: None }),
        ("ActionScript", Language { name: "ActionScript", language_type: LanguageType::Programming, color: Some("#882B0F"), group: None }),
        ("Zimpl", Language { name: "Zimpl", language_type: LanguageType::Programming, color: None, group: None }),
        ("ZAP", Language { name: "ZAP", language_type: LanguageType::Programming, color: Some("#0d665e"), group: None }),
        ("NASL", Language { name: "NASL", language_type: LanguageType::Programming, color: None, group: None }),
        ("Literate Haskell", Language { name: "Literate Haskell", language_type: LanguageType::Programming, color: None, group: Some("Haskell") }),
        ("Shen", Language { name: "Shen", language_type: LanguageType::Programming, color: Some("#120F14"), group: None }),
        ("APL", Language { name: "APL", language_type: LanguageType::Programming, color: Some("#5A8164"), group: None }),
        ("Augeas", Language { name: "Augeas", language_type: LanguageType::Programming, color: None, group: None }),
        ("X Font Directory Index", Language { name: "X Font Directory Index", language_type: LanguageType::Data, color: None, group: None }),
        ("LiveScript", Language { name: "LiveScript", language_type: LanguageType::Programming, color: Some("#499886"), group: None }),
        ("HAProxy", Language { name: "HAProxy", language_type: LanguageType::Data, color: None, group: None }),
        ("Diff", Language { name: "Diff", language_type: LanguageType::Data, color: None, group: None }),
        ("XML Property List", Language { name: "XML Property List", language_type: LanguageType::Data, color: None, group: Some("XML") }),
        ("nesC", Language { name: "nesC", language_type: LanguageType::Programming, color: Some("#94B0C7"), group: None }),
        ("OpenSCAD", Language { name: "OpenSCAD", language_type: LanguageType::Programming, color: None, group: None }),
        ("4D", Language { name: "4D", language_type: LanguageType::Programming, color: None, group: None }),
        ("ChucK", Language { name: "ChucK", language_type: LanguageType::Programming, color: None, group: None }),
        ("JavaScript", Language { name: "JavaScript", language_type: LanguageType::Programming, color: Some("#f1e05a"), group: None }),
        ("Propeller Spin", Language { name: "Propeller Spin", language_type: LanguageType::Programming, color: Some("#7fa2a7"), group: None }),
        ("PostCSS", Language { name: "PostCSS", language_type: LanguageType::Markup, color: None, group: Some("CSS") }),
        ("Mask", Language { name: "Mask", language_type: LanguageType::Markup, color: Some("#f97732"), group: None }),
        ("HolyC", Language { name: "HolyC", language_type: LanguageType::Programming, color: Some("#ffefaf"), group: None }),
        ("Rebol", Language { name: "Rebol", language_type: LanguageType::Programming, color: Some("#358a5b"), group: None }),
        ("Nearley", Language { name: "Nearley", language_type: LanguageType::Programming, color: Some("#990000"), group: None }),
        ("LSL", Language { name: "LSL", language_type: LanguageType::Programming, color: Some("#3d9970"), group: None }),
        ("Linker Script", Language { name: "Linker Script", language_type: LanguageType::Data, color: None, group: None }),
        ("SmPL", Language { name: "SmPL", language_type: LanguageType::Programming, color: Some("#c94949"), group: None }),
        ("RAML", Language { name: "RAML", language_type: LanguageType::Markup, color: Some("#77d9fb"), group: None }),
        ("Shell", Language { name: "Shell", language_type: LanguageType::Programming, color: Some("#89e051"), group: None }),
        ("Terra", Language { name: "Terra", language_type: LanguageType::Programming, color: Some("#00004c"), group: None }),
        ("VBScript", Language { name: "VBScript", language_type: LanguageType::Programming, color: Some("#15dcdc"), group: None }),
        ("Ruby", Language { name: "Ruby", language_type: LanguageType::Programming, color: Some("#701516"), group: None }),
        ("XQuery", Language { name: "XQuery", language_type: LanguageType::Programming, color: Some("#5232e7"), group: None }),
        ("Riot", Language { name: "Riot", language_type: LanguageType::Markup, color: Some("#A71E49"), group: None }),
        ("Charity", Language { name: "Charity", language_type: LanguageType::Programming, color: None, group: None }),
        ("Stylus", Language { name: "Stylus", language_type: LanguageType::Markup, color: None, group: Some("CSS") }),
        ("CWeb", Language { name: "CWeb", language_type: LanguageType::Programming, color: None, group: None }),
        ("ColdFusion CFC", Language { name: "ColdFusion CFC", language_type: LanguageType::Programming, color: None, group: Some("ColdFusion") }),
        ("BlitzBasic", Language { name: "BlitzBasic", language_type: LanguageType::Programming, color: None, group: None }),
        ("Vim Snippet", Language { name: "Vim Snippet", language_type: LanguageType::Markup, color: None, group: None }),
        ("HTA", Language { name: "HTA", language_type: LanguageType::Programming, color: Some("#a78649"), group: Some("HTML") }),
        ("Asymptote", Language { name: "Asymptote", language_type: LanguageType::Programming, color: Some("#4a0c0c"), group: None }),
        ("C2hs Haskell", Language { name: "C2hs Haskell", language_type: LanguageType::Programming, color: None, group: Some("Haskell") }),
        ("Fantom", Language { name: "Fantom", language_type: LanguageType::Programming, color: Some("#14253c"), group: None }),
        ("Marko", Language { name: "Marko", language_type: LanguageType::Markup, color: None, group: Some("HTML") }),
        ("D", Language { name: "D", language_type: LanguageType::Programming, color: Some("#ba595e"), group: None }),
        ("Quake", Language { name: "Quake", language_type: LanguageType::Programming, color: Some("#882233"), group: None }),
        ("Genshi", Language { name: "Genshi", language_type: LanguageType::Programming, color: None, group: None }),
        ("IRC log", Language { name: "IRC log", language_type: LanguageType::Data, color: None, group: None }),
        ("Vim script", Language { name: "Vim script", language_type: LanguageType::Programming, color: Some("#199f4b"), group: None }),
        ("CSS", Language { name: "CSS", language_type: LanguageType::Markup, color: Some("#563d7c"), group: None }),
        ("X10", Language { name: "X10", language_type: LanguageType::Programming, color: Some("#4B6BEF"), group: None }),
        ("Ioke", Language { name: "Ioke", language_type: LanguageType::Programming, color: Some("#078193"), group: None }),
        ("FreeMarker", Language { name: "FreeMarker", language_type: LanguageType::Programming, color: Some("#0050b2"), group: None }),
        ("Proguard", Language { name: "Proguard", language_type: LanguageType::Data, color: None, group: None }),
        ("GAML", Language { name: "GAML", language_type: LanguageType::Programming, color: Some("#FFC766"), group: None }),
        ("HTML+Razor", Language { name: "HTML+Razor", language_type: LanguageType::Markup, color: None, group: Some("HTML") }),
        ("MAXScript", Language { name: "MAXScript", language_type: LanguageType::Programming, color: Some("#00a6a6"), group: None }),
        ("Java", Language { name: "Java", language_type: LanguageType::Programming, color: Some("#b07219"), group: None }),
        ("Clojure", Language { name: "Clojure", language_type: LanguageType::Programming, color: Some("#db5855"), group: None }),
        ("ColdFusion", Language { name: "ColdFusion", language_type: LanguageType::Programming, color: Some("#ed2cd6"), group: None }),
        ("Public Key", Language { name: "Public Key", language_type: LanguageType::Data, color: None, group: None }),
        ("Modelica", Language { name: "Modelica", language_type: LanguageType::Programming, color: None, group: None }),
        ("sed", Language { name: "sed", language_type: LanguageType::Programming, color: Some("#64b970"), group: None }),
        ("VCL", Language { name: "VCL", language_type: LanguageType::Programming, color: Some("#148AA8"), group: None }),
        ("Ring", Language { name: "Ring", language_type: LanguageType::Programming, color: Some("#2D54CB"), group: None }),
        ("OpenCL", Language { name: "OpenCL", language_type: LanguageType::Programming, color: None, group: Some("C") }),
        ("Cloud Firestore Security Rules", Language { name: "Cloud Firestore Security Rules", language_type: LanguageType::Data, color: None, group: None }),
        ("ABNF", Language { name: "ABNF", language_type: LanguageType::Data, color: None, group: None }),
        ("Haml", Language { name: "Haml", language_type: LanguageType::Markup, color: None, group: Some("HTML") }),
        ("M", Language { name: "M", language_type: LanguageType::Programming, color: None, group: None }),
        ("Visual Basic .NET", Language { name: "Visual Basic .NET", language_type: LanguageType::Programming, color: Some("#945db7"), group: None }),
        ("XML", Language { name: "XML", language_type: LanguageType::Data, color: None, group: None }),
        ("Filebench WML", Language { name: "Filebench WML", language_type: LanguageType::Programming, color: None, group: None }),
        ("XCompose", Language { name: "XCompose", language_type: LanguageType::Data, color: None, group: None }),
        ("M4", Language { name: "M4", language_type: LanguageType::Programming, color: None, group: None }),
        ("Pep8", Language { name: "Pep8", language_type: LanguageType::Programming, color: Some("#C76F5B"), group: None }),
        ("ObjDump", Language { name: "ObjDump", language_type: LanguageType::Data, color: None, group: None }),
        ("fish", Language { name: "fish", language_type: LanguageType::Programming, color: None, group: Some("Shell") }),
        ("Click", Language { name: "Click", language_type: LanguageType::Programming, color: Some("#E4E6F3"), group: None }),
        ("SourcePawn", Language { name: "SourcePawn", language_type: LanguageType::Programming, color: Some("#5c7611"), group: None }),
        ("Svelte", Language { name: "Svelte", language_type: LanguageType::Markup, color: None, group: Some("HTML") }),
        ("DTrace", Language { name: "DTrace", language_type: LanguageType::Programming, color: None, group: None }),
        ("ZIL", Language { name: "ZIL", language_type: LanguageType::Programming, color: Some("#dc75e5"), group: None }),
        ("FLUX", Language { name: "FLUX", language_type: LanguageType::Programming, color: Some("#88ccff"), group: None }),
        ("LLVM", Language { name: "LLVM", language_type: LanguageType::Programming, color: Some("#185619"), group: None }),
        ("eC", Language { name: "eC", language_type: LanguageType::Programming, color: Some("#913960"), group: None }),
        ("Cap'n Proto", Language { name: "Cap'n Proto", language_type: LanguageType::Programming, color: None, group: None }),
        ("NPM Config", Language { name: "NPM Config", language_type: LanguageType::Data, color: None, group: Some("INI") }),
        ("REXX", Language { name: "REXX", language_type: LanguageType::Programming, color: None, group: None }),
        ("C#", Language { name: "C#", language_type: LanguageType::Programming, color: Some("#178600"), group: None }),
        ("E", Language { name: "E", language_type: LanguageType::Programming, color: Some("#ccce35"), group: None }),
        ("Limbo", Language { name: "Limbo", language_type: LanguageType::Programming, color: None, group: None }),
        ("Jupyter Notebook", Language { name: "Jupyter Notebook", language_type: LanguageType::Markup, color: Some("#DA5B0B"), group: None }),
        ("mIRC Script", Language { name: "mIRC Script", language_type: LanguageType::Programming, color: Some("#926059"), group: None }),
        ("Jasmin", Language { name: "Jasmin", language_type: LanguageType::Programming, color: None, group: None }),
        ("XSLT", Language { name: "XSLT", language_type: LanguageType::Programming, color: Some("#EB8CEB"), group: None }),
        ("Pan", Language { name: "Pan", language_type: LanguageType::Programming, color: Some("#cc0000"), group: None }),
        ("Tcsh", Language { name: "Tcsh", language_type: LanguageType::Programming, color: None, group: Some("Shell") }),
        ("wdl", Language { name: "wdl", language_type: LanguageType::Programming, color: Some("#42f1f4"), group: None }),
        ("Clean", Language { name: "Clean", language_type: LanguageType::Programming, color: Some("#3F85AF"), group: None }),
        ("SuperCollider", Language { name: "SuperCollider", language_type: LanguageType::Programming, color: Some("#46390b"), group: None }),
        ("Lean", Language { name: "Lean", language_type: LanguageType::Programming, color: None, group: None }),
        ("Tcl", Language { name: "Tcl", language_type: LanguageType::Programming, color: Some("#e4cc98"), group: None }),
        ("M4Sugar", Language { name: "M4Sugar", language_type: LanguageType::Programming, color: None, group: Some("M4") }),
        ("ShellSession", Language { name: "ShellSession", language_type: LanguageType::Programming, color: None, group: None }),
        ("Pickle", Language { name: "Pickle", language_type: LanguageType::Data, color: None, group: None }),
        ("Blade", Language { name: "Blade", language_type: LanguageType::Markup, color: None, group: Some("HTML") }),
        ("Ceylon", Language { name: "Ceylon", language_type: LanguageType::Programming, color: Some("#dfa535"), group: None }),
        ("Ignore List", Language { name: "Ignore List", language_type: LanguageType::Data, color: None, group: Some("INI") }),
        ("Open Policy Agent", Language { name: "Open Policy Agent", language_type: LanguageType::Programming, color: None, group: None }),
        ("JavaScript+CharCodeSubtract", Language { name: "JavaScript+CharCodeSubtract", language_type: LanguageType::Programming, color: Some("#f1e05a"), group: Some("JavaScript") }),
        ("Git Config", Language { name: "Git Config", language_type: LanguageType::Data, color: None, group: Some("INI") }),
        ("HTML+PHP", Language { name: "HTML+PHP", language_type: LanguageType::Markup, color: None, group: Some("HTML") }),
        ("Elm", Language { name: "Elm", language_type: LanguageType::Programming, color: Some("#60B5CC"), group: None }),
        ("Csound", Language { name: "Csound", language_type: LanguageType::Programming, color: None, group: None }),
        ("Altium Designer", Language { name: "Altium Designer", language_type: LanguageType::Data, color: None, group: None }),
        ("OpenQASM", Language { name: "OpenQASM", language_type: LanguageType::Programming, color: Some("#AA70FF"), group: None }),
        ("COLLADA", Language { name: "COLLADA", language_type: LanguageType::Data, color: None, group: None }),
        ("Befunge", Language { name: "Befunge", language_type: LanguageType::Programming, color: None, group: None }),
        ("X PixMap", Language { name: "X PixMap", language_type: LanguageType::Data, color: None, group: Some("C") }),
        ("OpenEdge ABL", Language { name: "OpenEdge ABL", language_type: LanguageType::Programming, color: None, group: None }),
        ("Oz", Language { name: "Oz", language_type: LanguageType::Programming, color: Some("#fab738"), group: None }),
        ("Boo", Language { name: "Boo", language_type: LanguageType::Programming, color: Some("#d4bec1"), group: None }),
        ("Parrot Assembly", Language { name: "Parrot Assembly", language_type: LanguageType::Programming, color: None, group: Some("Parrot") }),
        ("Darcs Patch", Language { name: "Darcs Patch", language_type: LanguageType::Data, color: None, group: None }),
        ("JavaScript+LongIdent", Language { name: "JavaScript+LongIdent", language_type: LanguageType::Programming, color: Some("#f1e05a"), group: Some("JavaScript") }),
        ("Roff Manpage", Language { name: "Roff Manpage", language_type: LanguageType::Markup, color: None, group: Some("Roff") }),
        ("EML", Language { name: "EML", language_type: LanguageType::Data, color: None, group: None }),
        ("Turing", Language { name: "Turing", language_type: LanguageType::Programming, color: Some("#cf142b"), group: None }),
        ("LFE", Language { name: "LFE", language_type: LanguageType::Programming, color: Some("#4C3023"), group: None }),
        ("C", Language { name: "C", language_type: LanguageType::Programming, color: Some("#555555"), group: None }),
        ("Csound Score", Language { name: "Csound Score", language_type: LanguageType::Programming, color: None, group: None }),
        ("Stan", Language { name: "Stan", language_type: LanguageType::Programming, color: Some("#b2011d"), group: None }),
        ("GAP", Language { name: "GAP", language_type: LanguageType::Programming, color: None, group: None }),
        ("Muse", Language { name: "Muse", language_type: LanguageType::Prose, color: None, group: None }),
        ("xBase", Language { name: "xBase", language_type: LanguageType::Programming, color: Some("#403a40"), group: None }),
        ("Windows Registry Entries", Language { name: "Windows Registry Entries", language_type: LanguageType::Data, color: None, group: None }),
        ("Cabal Config", Language { name: "Cabal Config", language_type: LanguageType::Data, color: None, group: None }),
        ("Hy", Language { name: "Hy", language_type: LanguageType::Programming, color: Some("#7790B2"), group: None }),
        ("DirectX 3D File", Language { name: "DirectX 3D File", language_type: LanguageType::Data, color: None, group: None }),
        ("Gentoo Ebuild", Language { name: "Gentoo Ebuild", language_type: LanguageType::Programming, color: None, group: Some("Shell") }),
        ("Nextflow", Language { name: "Nextflow", language_type: LanguageType::Programming, color: Some("#3ac486"), group: None }),
        ("dircolors", Language { name: "dircolors", language_type: LanguageType::Data, color: None, group: None }),
        ("Vala", Language { name: "Vala", language_type: LanguageType::Programming, color: Some("#fbe5cd"), group: None }),
        ("HTML+ECR", Language { name: "HTML+ECR", language_type: LanguageType::Markup, color: None, group: Some("HTML") }),
        ("GDScript", Language { name: "GDScript", language_type: LanguageType::Programming, color: Some("#355570"), group: None }),
        ("EJS", Language { name: "EJS", language_type: LanguageType::Markup, color: None, group: Some("HTML") }),
        ("Spline Font Database", Language { name: "Spline Font Database", language_type: LanguageType::Data, color: None, group: None }),
        ("SRecode Template", Language { name: "SRecode Template", language_type: LanguageType::Markup, color: Some("#348a34"), group: None }),
        ("QMake", Language { name: "QMake", language_type: LanguageType::Programming, color: None, group: None }),
        ("Grammatical Framework", Language { name: "Grammatical Framework", language_type: LanguageType::Programming, color: Some("#79aa7a"), group: None }),
        ("Faust", Language { name: "Faust", language_type: LanguageType::Programming, color: Some("#c37240"), group: None }),
        ("Lua", Language { name: "Lua", language_type: LanguageType::Programming, color: Some("#000080"), group: None }),
        ("Liquid", Language { name: "Liquid", language_type: LanguageType::Markup, color: None, group: None }),
        ("Lex", Language { name: "Lex", language_type: LanguageType::Programming, color: Some("#DBCA00"), group: None }),
        ("MediaWiki", Language { name: "MediaWiki", language_type: LanguageType::Prose, color: None, group: None }),
        ("Objective-C++", Language { name: "Objective-C++", language_type: LanguageType::Programming, color: Some("#6866fb"), group: None }),
        ("Cpp-ObjDump", Language { name: "Cpp-ObjDump", language_type: LanguageType::Data, color: None, group: None }),
        ("AsciiDoc", Language { name: "AsciiDoc", language_type: LanguageType::Prose, color: None, group: None }),
        ("Formatted", Language { name: "Formatted", language_type: LanguageType::Data, color: None, group: None }),
        ("RMarkdown", Language { name: "RMarkdown", language_type: LanguageType::Prose, color: None, group: None }),
        ("Cirru", Language { name: "Cirru", language_type: LanguageType::Programming, color: Some("#ccccff"), group: None }),
        ("F*", Language { name: "F*", language_type: LanguageType::Programming, color: Some("#572e30"), group: None }),
        ("Raku", Language { name: "Raku", language_type: LanguageType::Programming, color: Some("#0000fb"), group: None }),
        ("Pod", Language { name: "Pod", language_type: LanguageType::Prose, color: None, group: None }),
        ("Logtalk", Language { name: "Logtalk", language_type: LanguageType::Programming, color: None, group: None }),
        ("XPages", Language { name: "XPages", language_type: LanguageType::Data, color: None, group: None }),
        ("Nemerle", Language { name: "Nemerle", language_type: LanguageType::Programming, color: Some("#3d3c6e"), group: None }),
        ("SWIG", Language { name: "SWIG", language_type: LanguageType::Programming, color: None, group: None }),
        ("Ecere Projects", Language { name: "Ecere Projects", language_type: LanguageType::Data, color: None, group: Some("JavaScript") }),
        ("RDoc", Language { name: "RDoc", language_type: LanguageType::Prose, color: None, group: None }),
        ("Markdown", Language { name: "Markdown", language_type: LanguageType::Prose, color: None, group: None }),
        ("Awk", Language { name: "Awk", language_type: LanguageType::Programming, color: None, group: None }),
        ("Fancy", Language { name: "Fancy", language_type: LanguageType::Programming, color: Some("#7b9db4"), group: None }),
        ("SugarSS", Language { name: "SugarSS", language_type: LanguageType::Markup, color: None, group: Some("CSS") }),
    ],
};

