// @generated by codegen.rs from specializations.yml — do not hand-edit

pub(crate) struct SpecializationRule {
    pub variant: &'static str,
    pub base: Option<&'static str>,
    pub pattern: &'static str,
}

pub(crate) static SPECIALIZATIONS: &[SpecializationRule] = &[
    SpecializationRule { variant: "VBScript+HTMLDecoy", base: None, pattern: "(?i)^\\s*'<!DOCTYPE\\s+html" },
    SpecializationRule { variant: "HTA", base: None, pattern: "(?i)<HTA:APPLICATION\\b" },
];
